### ISSUE TITLE
Pretalx feedback links invalid

### ISSUE THREAD

**Issue by mirabilos** [EventFahrplan/EventFahrplan#114]
404 @ https://frab.cccv.de/en/35C3/public/events/110/feedback/new

**Comment by johnjohndoe** [comment]
@mirabilos It looks like that this specifically concerns the events aggregated from the smaller stages besides Adams ... Eliza. @voc, @saerdnaer, @raphaelm, @rixx, can you tell if there is specific feedback links being provides by those stages which use Pretalx?

**Comment by johnjohndoe** [comment]
Thank you for the reminder. I don't think it is necessary to change the XML. The app is prepared to handle pure Preltalx schedule data but not schedule data from mixed sources as it is the case at 35C3.

**Comment by saerdnaer** [comment]
Hmm, maybe we should think about an additional (optional) attribute on the event, containing the feedback URL for that talk....

**Comment by johnjohndoe** [comment]
@saerdnaer The only solution I could think of at the moment which works without an app release would be if someone would actually set up a redirect for each of the non-existing URLs.

**Comment by johnjohndoe** [comment]
@saerdnaer @rixx For now [I fixed the feedback for Pretalx events](https://github.com/EventFahrplan/EventFahrplan/pull/118/commits/9f9d57221a89c1c6fbc6fde886332490d2669952). We will need to talk about events imported from the wiki at some point and revisit this topic.

**Comment by johnjohndoe** [comment]
:link: https://github.com/voc/schedule/issues/39

**Comment by johnjohndoe** [comment]
:link: [Frab/Pretalx-Feedback URL in aggregiertem schedule.xml/json
](https://git.cccv.de/hub/hub/-/issues/430)
