### ISSUE TITLE
Going back from the event details won't return to the last state

### ISSUE THREAD

**Issue by alexanderadam** [EventFahrplan/EventFahrplan#116]
In addition to the performance issue (#108):

Going back from detail view won't remember the last position state. For example if someone has a few favourites were scrolling is necessary, returning from a event detail won't return to the correct scroll position. Instead it goes to the top, making it necessary to scroll down over and over again when you want to look up a few events in the future.

The same is true for the schedule view.

**Comment by johnjohndoe** [comment]
Fixed in version 1.38.3. Please update, check and update/close your issue here.

**Comment by johnjohndoe** [comment]
Closing this for now. Please comment here if there is open questions.
