### ISSUE TITLE
Restrict usage while screen is locked

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#127]
# Environment
- App version: [v.1.38.4](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.38.4)

# How to reproduce
1. Launch the app.
2. Lock the device.
3. Use the app on the **lock screen**.

# Observed behavior
- **All screens** of the app can be used.

# Expected behavior
- Only the **schedule view** and the **event details** view can be visited.
- Lock screen users are **not** be able to visit the **app settings** where they can change the schedule URL.
- Lock screen users are **not** be able to visit the **alarms list** where all alarms can be deleted.
- Lock screen users are **not** be able to visit the **favorites list** where all alarms can be deleted.

# Devices
- Please check both phones and tablets as the screens are set up differently.

# Related
- This feature has been added in 1be512c101c6d4df07a74269c41856289c968229 and released with [v.1.38.4](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.38.4).

**Comment by AniVerma17** [comment]
I am working on this.
