### ISSUE TITLE
Day selection lost on rotation (> Android 6.0)

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#14]
- This issue was already reported by @ninov and a first fix can be found in https://github.com/ligi/CampFahrplan/pull/8.
- I could narrow the problem down: it only occurs on devices running Android 7.0 or Android 8.0.

# How to reproduce
1. Select day three
2. Rotate device

## Observed behavior
- Day one is selected
- Reproduced on Android 8.0

![rotation-android-8 0](https://user-images.githubusercontent.com/144518/30002579-fcf71246-90ac-11e7-91ae-47ecb0286de9.gif)

## Expected behavior
- Day three is still selected
- Reproduced on Android 6.0

![rotation-android-6 0](https://user-images.githubusercontent.com/144518/30002580-0202e30a-90ad-11e7-88a4-3f7bba55e00c.gif)

**Comment by Tomatower** [comment]
fixed in pr #41

**Comment by johnjohndoe** [comment]
# Intermediate analysis

- The [deprecated `ActionBar.OnNavigationListener.onNavigationItemSelected()`](https://developer.android.com/reference/android/app/ActionBar.OnNavigationListener.html) callback for the day selection dropdown returns an item position of `1` after a device rotation on Android 7.1.1.
- Android 6.0 to be investigated.
