### ISSUE TITLE
Assertion library update

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#141]
# Motivation
- Due to the deprecation of [AssertJ Android](https://github.com/square/assertj-android) in [August 2017](https://github.com/square/assertj-android/commit/7d4da5c468bce780e43c243853d5b8f1e7b93135) a replacement should be found.

# Hints
- Find out if [AssertJ](https://github.com/assertj/assertj) will still be used as a transitive dependency or fully replaced by a new library.
- Keep in mind that the new library must be usable both from Kotlin and Java.

# Options
- [Google Truth](https://github.com/google/truth)
- [AssertJ](https://github.com/assertj/assertj)
- [Strikt](https://github.com/robfletcher/strikt)
- [Atrium](https://github.com/robstoll/atrium)
- [Kluent](https://github.com/MarkusAmshove/Kluent)
- [assertk](https://github.com/willowtreeapps/assertk)
- tbc.

# Related
- [Issue #251: Modernize testing infrastructure](https://github.com/EventFahrplan/EventFahrplan/issues/251)

# Resources
- [Getting Started with AndroidX Test](https://victoriagonda.com/talks/androidx_test.html)
- [Write a comparison to Kluent, AssertK, Strikt, Atrium, Kotest, other Kotlin assertion libraries?](https://github.com/google/truth/issues/849)
- [Kotlin Assertion Library Comparison](https://github.com/phellipealexandre/KotlinAssertionLibraryComparison)
- [Kotlin assertion libraries - JUnit, Hamkrest and Strikt](https://www.youtube.com/watch?v=lyDOPNSqYoo)

**Comment by akarsh** [comment]
From issues in the repo - [Google Truth](https://github.com/google/truth), I see the [Kotlin support](https://github.com/google/truth/issues/404) is an open issue.

I found a Kotlin library - [Atrium](https://github.com/robstoll/atrium) but there is no [comparison of Google Truth vs Atrium](https://google.github.io/truth/comparison.html) on Google Truth website.
