### ISSUE TITLE
adding jvm arguments to the project

### ISSUE THREAD

**Issue by akarsh** [EventFahrplan/EventFahrplan#146]
Follow-up on: https://github.com/EventFahrplan/EventFahrplan/pull/145#discussion_r283492209

By default Android Studio adds JVM arguments into the `gradle.properties` file into every project.
As the `gradle.properties` file is ignored by Git a common solution has to be found i.e a configuration that can be included in the two build types.

Note: The [CI configuration file](https://github.com/EventFahrplan/EventFahrplan/blob/master/.travis.yml) for this project has the following JVM arguments:

``` properties
# Reduce memory usage / avoid OutOfMemoryError with Gradle 4.10.3
- echo "org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:MaxPermSize=768m" >> gradle.properties
```

**Comment by johnjohndoe** [comment]
> By default, Android Studio has a maximum heap size of 1280MB. If you are working on a large project, or your system has a lot of RAM, you can improve performance by increasing the maximum heap size for Android Studio processes, such as the core IDE, Gradle daemon, and Kotlin daemon.
>
> Android Studio automatically checks for possible heap size optimizations and notifies you if it detects that performance can be improved.

Source: https://developer.android.com/studio/intro/studio-config#adjusting_heap_size

From my understanding it make sense to keep the JVM arguments to the individual developer because each developer machine potentially has difference hardware resp. capabilities. @akarsh If you agree I ask you to close the issue.

**Comment by akarsh** [comment]
True I agree with you.
I am closing this issue.
