### ISSUE TITLE
CCCamp 2019 / Deployment / F-Droid

### ISSUE THREAD

**Issue by jspricke** [EventFahrplan/EventFahrplan#149]
Hey, I see a 1.39.1 version on Google Play with the camp data and design. Could you publish and tag this on Github so we could get it through F-Droid?

Thanks!

**Comment by johnjohndoe** [comment]
Hi @jspricke.
The [cccamp2019](https://github.com/johnjohndoe/CampFahrplan/tree/cccamp2019) branch is not yet merged into `master`. I will do this later. The tags are pushed - here is the [v.1.39.1-CCCamp-Edition](https://github.com/johnjohndoe/CampFahrplan/releases/tag/v.1.39.1-CCCamp-Edition) tag.
I will publish the app via F-Droid - as promised in [this tweet](https://twitter.com/tbsprs/status/1158447414644301824) - as soon as I have time to do so.

**Comment by jspricke** [comment]
It should be enough to push the tag to this repo to get it updated on F-Droid. I can take care to update the description if you don't have the time.

**Comment by johnjohndoe** [comment]
I prefer to keep the tags for this repository such as `v.1.39.0` separate from the tags with `-something`. The hyphen-less tags are observed by F-Droid for the 3xC3 app which automatically updates once a tag in that format is pushed.

What I plan to do for the Camp is to point to the `v.1.39.x-CCCamp-Edition` tags in the forked repository.

**Comment by johnjohndoe** [comment]
Status update: I am working on publishing the Camp Schedule 2019 on F-Droid. The process is [still ongoing](https://gitlab.com/fdroid/fdroiddata/merge_requests/5250).

**Comment by jspricke** [comment]
Thanks for the update. What about publishing nightly builds for the 
Camp? There is a guide here:

https://f-droid.org/en/docs/Publishing_Nightly_Builds/

**Comment by johnjohndoe** [comment]
Status update: The new app entry has been merged at Aug 15, 2019. Now we have to wait for the F-Droid pipeline.

Since it is usually pretty packed it might make sense to launch a dedicated F-Droid repository for the Camp 2019. @schildbach suggested this to me yesterday, too. For 35C3 such as [repository](https://fdroid.gitlab.io/35c3/fdroid/repo/) had been hosted by @bubu. I will not do this myself. If anyone wants to do this they are very welcome to do so.

@jspricke With regards to nightly builds I like to thank you for the hint. However, I don't see a use case for it at this point in time. I will probably not work so much on the app during Camp. As nobody else has joined development on the project there will be no outcome to serve.

**Comment by Bubu** [comment]
I'd like to not be responsible for providing the F-Droid repo this year, I think @jspricke was working on it?

I'll be at camp though, see you there.

**Comment by jspricke** [comment]
For card10 there is already a nightly repo here: https://git.card10.badge.events.ccc.de/card10/companion-app-android-nightly

I don't think it makes sense to have an extra F-Droid repo for the Fahrplan if you don't plan to work on it. So either it gets into the main repo in time or I would propose to go the nightly way as well.

**Comment by johnjohndoe** [comment]
To clarify: There have always been 1-3 releases during the Congress or Camp which then need to go live as fast as possible to still reach users which was impossible with the main F-Droid repository in the last years. Only Google Play users benefited from these updates. Therefore, at 35C3 the separate repository was very helpful. I don't expect many more releases, though.

**Comment by schildbach** [comment]
> For card10 there is already a nightly repo here: https://git.card10.badge.events.ccc.de/card10/companion-app-android-nightly

The above repo is not for releases, only for our CI builds.

I think releases of app camp related apps should go into a "camp repo", and should be signed by proper release keys.

**Comment by jspricke** [comment]
>I think releases of app camp related apps should go into a "camp repo", and should be signed by proper release keys.

Agreed.

@eighthave proposed to have a general https://fdroid.gitlab.io/ccc repo 
to reuse in future. Would that fit all of you?

Should I build and sign all apps or do you want to send me signed apks 
via a secure channel (gpg mail?) so they are compatible with the Play 
store?

@schildbach: we would need some tagging/version code convention in case 
I should build the app.

P.S.: Hope it's fine to discuss this over here.

**Comment by schildbach** [comment]
Sounds good to me!

Regarding the card10 app, there won't be a Play Store release. It's too late for Camp. Yes I guess at some point we will tag a first version. `v0.1`? I'm fine if you sign it, but let's see what others think about this point.

**Comment by johnjohndoe** [comment]
Sounds fine to me. I guess signing the app as it is done by the main F-Droid pipeline is sufficient. I am happy if you can take care of this. I won't have time to work on anything before Aug 21 evening.

**Comment by dbrgn** [comment]
A reusable ccc repo sounds like a good idea. Otherwise this discussion will happen every year before congress :)

**Comment by johnjohndoe** [comment]
Okay. Let's do it. Who can set up the repository? @eighthave, can you?

**Comment by jspricke** [comment]
Done: https://fdroid.gitlab.io/ccc/fdroid/repo?fingerprint=1F2ECC52D4A5C49586FDDC0A3E57E2F4C9B5B3041DB1EC455747A84344DCA10E

**Comment by johnjohndoe** [comment]
@jspricke HTTP 404.

**Comment by Bubu** [comment]
@johnjohndoe it should open in fdroid on a phone where its installed.

Otherwise look at https://fdroid.gitlab.io/ccc for other ways to add the repo.

**Comment by johnjohndoe** [comment]
Ah, sorry for my confusion. Thank you for updating the wiki.
Thanks to everybody. I guess we can close the issue now?

**Comment by Bubu** [comment]
@johnjohndoe Could you match Tags and version names of the app for fdroid to pick up the updates automatically?

Currently it's 
  - versionName: 1.39.1 (CCCamp Edition)
    commit: v.1.39.1-CCCamp-Edition

**Comment by johnjohndoe** [comment]
@Bubu I matched the Git tag and the `versionName` here: b4046e2c4d8b0b79df060a070434c3f96cfd280d.

**Comment by alexanderadam** [comment]
> @johnjohndoe it should open in fdroid on a phone where its installed.
> 
> Otherwise look at https://fdroid.gitlab.io/ccc for other ways to add the repo.

The mentioned link on this page returns 404:

https://fdroid.gitlab.io/ccc/fdroid/repo?fingerprint=1F2ECC52D4A5C49586FDDC0A3E57E2F4C9B5B3041DB1EC455747A84344DCA10E

**Comment by alexanderadam** [comment]
> @johnjohndoe it should open in fdroid on a phone where its installed.
> 
> Otherwise look at https://fdroid.gitlab.io/ccc for other ways to add the repo.

We tested it here on different devices and it doesn't open in fdroid.
The link on the page naturally also returns 404.

**Comment by jspricke** [comment]
Am 22. August 2019 12:01:24 MESZ schrieb Alexander Adam <notifications@github.com>:
>> Otherwise look at https://fdroid.gitlab.io/ccc for other ways to add
>the repo.
>
>The mentioned link on this page returns 404:

That's correct, just add it to F-Droid.

**Comment by Bubu** [comment]
@johnjohndoe auto update's still not working. I think because of `"${defaultConfig.versionName}` this variable which fdroid can't parse.

If there's more than one further update 'planned' during camp would you consider just replacing this variable?

**Comment by Bubu** [comment]
IN other news, the 1.39.2 version is release in the f-droid repo now.

**Comment by johnjohndoe** [comment]
Thank you. I can put the versionName in manually for the next update. Or we teach F-Droid to deal with it. It could be a search and replace command to be run before.

**Comment by johnjohndoe** [comment]
@Bubu The `versionName` is fixed in c2a9ccb9749f1639a9d8ad6a4018a1f5a95a2172.
A new version `v.1.39.3-CCCamp-Edition` can be pushed to F-Droid now.

**Comment by Bubu** [comment]
On August 23, 2019 7:49:43 PM GMT+02:00, Tobias Preuss <notifications@github.com> wrote:
>@Bubu The `versionName` is fixed in
>c2a9ccb9749f1639a9d8ad6a4018a1f5a95a2172.
>A new version `v.1.39.3-CCCamp-Edition` can be pushed to F-Droid now.

Thank you. Done.

**Comment by johnjohndoe** [comment]
Hi @Bubu and @jspricke.

The [main F-Droid repository](https://gitlab.com/fdroid/fdroiddata/) currently lists [`Version 1.39.1 (CCCamp Edition)`](https://f-droid.org/en/packages/info.metadude.android.cccamp.schedule/) which only serves the two main stages. I did not notice that the main deployment pipeline published an app version during the Camp. I am guessing we thereby missed out to reach a lot of F-Droid users with the latest version.

Can you please merge your fork of fdroiddata into the [main repository](https://gitlab.com/fdroid/fdroiddata/)? I would like to see the latest app version being available "upstream", too.

Further, I plan to revert the [`versionName` change](https://github.com/EventFahrplan/EventFahrplan/commit/c2a9ccb9749f1639a9d8ad6a4018a1f5a95a2172) which you ask me for to automate the F-Droid update process. To ensure that the automatism still works I prepared the [this change](https://gitlab.com/tbsprs/fdroiddata/commits/cccamp-schedule-2019) to the fdroiddata file. You are invited to comment/improve the change - it is still a draft.

**Comment by Bubu** [comment]
@johnjohndoe https://gitlab.com/tbsprs/fdroiddata/commits/cccamp-schedule-2019 won't work for autoupdates I think. `fdroid checkupdates` just parses the build.gradle file with regexes, this happens completely independent from build/prebuild steps.

**Comment by johnjohndoe** [comment]
@Bubu I don't understand why the string substitution won't work. For the _Congress_ app a similar replacement has happened as you can see in the [configuration file](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/info.metadude.android.congress.schedule.yml). Please explain the problem which you see in more details.

**Comment by Bubu** [comment]
@johnjohndoe building works fine, automatic updates don't work with any dynamic gradle features. Sorry if that wasn't clear.

fdroid checkupdates is just currently very limited in functionality. There are plans to fix this but it won't be done until next congress for example.

**Comment by johnjohndoe** [comment]
@Bubu & @jspricke 

> Can you please merge your fork of fdroiddata into the main repository? I would like to see the latest app version being available "upstream", too.

**Comment by Bubu** [comment]
On vacation until 22nd.

**Comment by johnjohndoe** [comment]
[Version 1.40.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.40.0) has now appeared on [F-Droid](https://f-droid.org/en/packages/info.metadude.android.cccamp.schedule/). I therefore close this issue and like to thank everyone once again for their support.
