### ISSUE TITLE
Wrong URLs / Not using provided field.

### ISSUE THREAD

**Issue by n0emis** [EventFahrplan/EventFahrplan#150]
# Observed behavior
Under `Event online` there is a selfgenerated url to the Event.
When using combined schedules/wiki-events this url does not work.

# Expected behavior
At least in the files generated by https://github.com/voc/schedule/ e.g. at https://data.c3voc.de/camp2019/everything.schedule.xml there is always a `url` filed with a working address. it would be nice if the app used this.

**Comment by johnjohndoe** [comment]
Thank you for reporting this. It should be rather easy to fix. I suggest looking into EventUrlComposer. Maybe this change is related: https://github.com/voc/schedule/pull/46. I probably have time to work on this at Aug 20 night. Therefore, if anyone wants to fix this before - you are welcome.

**Comment by n0emis** [comment]
The change in voc/schedule#46 is there to include the url of wiki-events in the afformentioned field.

**Comment by n0emis** [comment]
I have now taken a look at it and judging the travis-tests is should now work.
I've also modified the tests because I think there is no reason that the composed url should be preferred over the original stated one.

**Comment by johnjohndoe** [comment]
Resolved here: b14f6c36037edc9d458ae5138b3d3d9f13827767.
