### ISSUE TITLE
Update Portuguese translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#169]
Since the [initial contribution of the Portuguese translation](https://github.com/EventFahrplan/EventFahrplan/commit/78c1bf7992f446dc3640e32b7a055074052c7246) :brazil: by @grote and friends a few strings have been added or changed. It would be great to have the missing strings completed.

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

- [ ] Add missing translations in `app/src/main/res` (ignore `placeholder` strings)
- [ ] Optional: Review and fix errors in existing translations
- [ ] Optional: Add missing translations in `app/src/ccc35c3/res` (becomes visible when you change the _Build Variant_)
- [ ] Optional: Add missing translations in `app/src/cccamp2019/res` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- [Contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md)

**Comment by myluco** [comment]
Can I work on that?

**Comment by johnjohndoe** [comment]
@myluco You can join reviewing this pull request https://github.com/EventFahrplan/EventFahrplan/pull/171. That would be nice since I don't speak Portuguese.
