### ISSUE TITLE
Complete and update French translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#170]
Since the [contribution of the French translation](https://github.com/EventFahrplan/EventFahrplan/commit/c2df832d0d32be50612f1be4f327d84364d0c79f) :fr: by @BoFFire a few strings have been added or changed. It would be great to have the missing strings completed.

The _Translation Editor_ in _Android Studio_ let's you easily identify the **missing** translations as shown in the screenshot. Existing translations might be **outdated** or **incomplete** and must be checked critically.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [x] Add missing translations in `app/src/main/res/values-fr` (ignore `placeholder` strings)
- [x] Review and complete and update existing translations
  - Files to cover: `preferences.xml`, `strings.xml`
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Do not modify, commit files outside of the `-fr` folder.
  - Ensure that [`plurals`](https://developer.android.com/guide/topics/resources/string-resource#Plurals) are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [x] Add missing translations in `app/src/ccc36c3/res/values-fr` (becomes visible when you change the _Build Variant_)
- [ ] Add missing translations in `app/src/cccamp2019/res/values-fr` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by BoFFire** [comment]
Nice !

**Comment by sebastienvermeille** [comment]
Hi @johnjohndoe I am a french speaker I can handle this issue and send a PR 1st of oct. if you agree :)

**Comment by sebastienvermeille** [comment]
haha may I ask you to review the PR the 1st of october fast? It is for Hacktoberfest I would like to earn a free tshirt :dancing_men:

**Comment by Toinane** [comment]
still on the translation @sebastienvermeille ?

**Comment by BoFFire** [comment]
Done here ;)
https://rosette.eu.org/projects/evenfahrplan/eventfahrplan/

**Comment by johnjohndoe** [comment]
@BoFFire Are you going to submit a pull request here on GitHub?

**Comment by Omicron666** [comment]
working on it #hacktobeerfest ^^
