### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#174]
It would be nice to have a Russian translation of the app. :ru: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [x] Add new translations in `app/src/main/res/values-ru` (ignore `placeholder` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left
- [x] Optional: Add new translations in `app/src/ccc35c3/res/values-ru` (becomes visible when you change the _Build Variant_)
- [x] Optional: Add new translations in `app/src/cccamp2019/res/values-ru` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- [Contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md)

**Comment by Ikhiloya** [comment]
Hi I’d like to take this

**Comment by johnjohndoe** [comment]
@Ikhiloya You are welcome to complete the optional items which @today- has not translated in #183.

**Comment by Ikhiloya** [comment]
okay. thanks

**Comment by Ikhiloya** [comment]
Any particular translator used here? I'm thinking of using google translate

**Comment by johnjohndoe** [comment]
@Ikhiloya I hope this is a bad joke. The translation should be done by a native speaker.

**Comment by Ikhiloya** [comment]
I didn’t know, I’m not a native speaker. I can’t handle it anymore then. Thanks

**Comment by johnjohndoe** [comment]
Okay. Thank you for the clarification. Then this issue is again free to be resolved by someone else.

**Comment by today-** [comment]
@yanicka 
Translation was completed in this PR https://github.com/EventFahrplan/EventFahrplan/pull/183/files

**Comment by johnjohndoe** [comment]
Not completely. Optional todos are still open.

**Comment by JekRock** [comment]
@johnjohndoe I can add Ukrainian translation if you're interested in it. Sorry for writing it here, haven't found the issue for that.

**Comment by johnjohndoe** [comment]
@JekRock Does it differ significantly from Russian?

**Comment by JekRock** [comment]
@johnjohndoe they are similar only if you know both. Most of Ukrainians speak Russian. But most people from Russia don't speak Ukrainian.

**Comment by johnjohndoe** [comment]
@JekRock I appreciate your offer. Please create a pull request following the description in this issue and the contribution guidelines. I will have time to review it at the end of the month.
