### ISSUE TITLE
Complete and update Italian translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#175]
It would be nice to have an Italian translation of the app. :it: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [ ] Update or add new translations in `app/src/main/res/values-it`
  - Take `app/src/main/res/values` (English) as a reference.
  - Files to cover: `preferences.xml`, `strings.xml`
  - Ignore strings with the `translatable="false"` attribute and `placeholder` strings.
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Do not modify, commit files outside of the `-it` folder.
  - Ensure that [`plurals`](https://developer.android.com/guide/topics/resources/string-resource#Plurals) are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [ ] Review and complete and update translations in `app/src/main/res/values-it` (ignore `placeholder` strings)
- [ ] Add new translations in `app/src/rc3/res/values-it` (becomes visible when you change the _Build Variant_)
- [ ] Add new translations in `app/src/ccc36c3/res/values-it` (becomes visible when you change the _Build Variant_)
- [ ] Add new translations in `app/src/cccamp2019/res/values-it` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by amarziali** [comment]
Hi @johnjohndoe . I may help on this one being italian native ;)

**Comment by amarziali** [comment]
Fell free to assign me. I'll do a pull request for hackoctoberfest

**Comment by johnjohndoe** [comment]
Please mind that I will **not** be able to reply quickly since I am on vacation for a while (Oct 3-31).

**Comment by amarziali** [comment]
No issues. BTW I just opened the PR. On your hands right now..and have a good holidays ;)

**Comment by johnjohndoe** [comment]
Left over to translate: Strings for `ccc35c3` and `cccamp2019` flavors.

**Comment by johnjohndoe** [comment]
Translations are now managed on Crowdin. See #551.
