### ISSUE TITLE
Add Dutch translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#176]
It would be nice to have a Dutch translation of the app. :netherlands: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [ ] Add new translations in `app/src/main/res/values-nl` (ignore `placeholder` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left
- [ ] Optional: Add new translations in `app/src/ccc35c3/res/values-nl` (becomes visible when you change the _Build Variant_)
- [ ] Optional: Add new translations in `app/src/cccamp2019/res/values-nl` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- [Contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md)

**Comment by spmvanmierlo** [comment]
You can assign me here as well. Glad to help you out!
