### ISSUE TITLE
Update Portuguese translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#180]
Since the [update of the Portuguese translation](https://github.com/EventFahrplan/EventFahrplan/commit/4357c5a22792b85509c273b812d474ea7e3a11f5) by @adrianoapj a few strings have been added. It would be great to have the missing strings completed.

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

- [x] Add missing translations in `app/src/main/res` (ignore `placeholder` strings)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- [Contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md)
- [Issue #171: Portuguese translation updated.](https://github.com/EventFahrplan/EventFahrplan/pull/171)

**Comment by adrianoapj** [comment]
Can I do that? Should I add a lecture_list_item_language_portuguese_content_description string?

**Comment by johnjohndoe** [comment]
@adrianoapj Good idea. Since the app has been used in Portuguese speaking countries we could have it built-in. You need to extend the corresponding code in `Lecture#getLanguageContentDescription`, too. See #179.

**Comment by johnjohndoe** [comment]
Resolved with c60f58686b4237724cd13f3766393070d2ebc2df.
