### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by aseggemu-fyber** [EventFahrplan/EventFahrplan#189]
# Environment
 - Android Studio 3.5.1
 - Build #AI-191.8026.42.35.5900203, built on September 25, 2019
 - JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
 - JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - macOS 10.14.6
 - Gradle version: 5.6.2
 - Android Gradle plugin Version: 3.5.1

# How to reproduce
1. Clone the project- EventFahrplan
2. Branch: master
3. Open Android Studio and click on `import project(...)`

# Observed behavior
- Gradle sync failed with the following error
```Could not resolve all dependencies for configuration ':app:ccc35c3DebugRuntimeClasspath'.
Could not determine artifacts for com.github.ligi.snackengage:snackengage-playrate:0.22: Skipped due to earlier error
```

# Expected behavior
- The project should sync without any error.
- Run the app on the device and simulator.

# Related
- The library [snackengage-playrate](https://github.com/ligi/SnackEngage/tree/master/snackengage-playrate) mentioned in the error console was having different Android Studio/Gradle version.

**Comment by Talisantos** [comment]
I will work on this
