### ISSUE TITLE
TraceDroid-1.1.jar prevents F-Droid inclusion

### ISSUE THREAD

**Issue by grote** [EventFahrplan/EventFahrplan#19]
F-Droid doesn't allow arbitrary `jar` files in the source tree, because it needs to ensure that the source code for the entire app is available and free.

It seems that `TraceDroid-1.1.jar` is coming from https://github.com/ligi/tracedroid

Why don't you simply include it like this instead of using a jar?

```groovy
dependencies {
    compile 'org.ligi:tracedroid:1.4'
}
```

**Comment by johnjohndoe** [comment]
I believe the library was only available as a `jar` when I added it in dd80e8d2209393497f9881dc6740574f60f66e26 - I do not quite remember. We can certainly use the dependency reference instead. Do you want to prepare a pull request?
