### ISSUE TITLE
Translation for notification channel names does not apply

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#195]
# Environment
- App version: [1.40.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.40.0)
- Android version: 10
- Branch: master
- Device: Pixel 2

# How to reproduce
1. Set your system language to German
2. Visits the "Einstellungen" screen and tap "Benachrichtigungen anpassen ...".
3. The notifications screen shows two notifications channels with their German name.
  ![Notifications-Channels-DE](https://user-images.githubusercontent.com/144518/68027208-1187c700-fcb2-11e9-8e1b-6f52557d133a.png)
4. Switch the system language to English, and resume the notifications screen.

# Observed behavior
- Notification channels names are rendered in German.
  ![Notifications-Channels-EN](https://user-images.githubusercontent.com/144518/68027229-1d738900-fcb2-11e9-8dfb-9683dfc0f994.png)

# Expected behavior
- Notification channels names are rendered in English.

# Hints
- See `NotificationHelper`.

# Related
- [Issue #133: Provide notifications settings shortcut in app settings.](https://github.com/EventFahrplan/EventFahrplan/pull/133)

**Comment by johnjohndoe** [comment]
@ideadapt Can you comment here please - such as "I will work on this" - then I can assign you to the issue.

**Comment by ideadapt** [comment]
I've been working on this in #225
