### ISSUE TITLE
Use white textcolours for dark background colours

### ISSUE THREAD

**Issue by Wikinaut** [EventFahrplan/EventFahrplan#20]
Improve readability by using white textcolour for "dark" backgrounds.

See https://en.wikipedia.org/w/index.php?title=Web_colors&oldid=651498112#X11_color_names (*) for a nice overview (when to use black, when to use white textcolour).

(*) newer versions of this page do unfortunately not visualize the contrast differences.

See here for something different: random generation of "nice" colours: 

* https://randomcolor.llllll.li/
* repo https://github.com/davidmerfield/randomColor

**Comment by fgau** [comment]
![screenshot_20171219-081027](https://user-images.githubusercontent.com/8269366/34146980-5f37f90a-e49c-11e7-94da-0c9be42c59ba.png)
event_title I think needs to change to white

**Comment by johnjohndoe** [comment]
I think I might be able to look into that Wednesday night (20.12) or Friday (22.12.).

**Comment by Wikinaut** [comment]
@fgau your screenshot: perfect!

**Comment by Wikinaut** [comment]
Sorry, not okay! The new version has for example "Dude, you broke the future" almost unreadable on my Android (white text on bright yellow background). Please use black textcolor for bright backgrounds.

**Comment by johnjohndoe** [comment]
@Wikinaut Thank you for the feedback. Right now I am rolling out the white text color in version 1.33.1. I might be able to adjust colors again for the next release. Meanwhile, I would be interested in which device you are using (model, brightness settings, redshift app, ...) so I can test the app in your environment.

**Comment by Wikinaut** [comment]
@johnjohndoe HUAWEI P8 LITE 2017
And pls. again, I mean, that 

* **white** text for dark backgrounds ; **and***
* **black** text for bright backgrounds.

Example: see the **color** **names** in the table on https://en.wikipedia.org/w/index.php?title=Web_colors&oldid=651498112#X11_color_names

**Comment by Wikinaut** [comment]
Bitte die Farbe für den Text des Tracks (rechts untere Ecke auch noch verbessern).
