### ISSUE TITLE
36C3 / F-Droid deployment

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#202]
# Description
- This issue has the purpose to collect all **questions and answers** related to the [F-Droid](https://f-droid.org) deployment of the **36C3** flavor of the schedule app.

# F-Droid repository for 36C3
- Add this repository to your F-Droid app in order to retrieve the **latest version** of the 36C3 Schedule app.  :arrow_right: [CCC F-Droid repository](https://fdroid.gitlab.io/ccc/) 
- The [official F-Droid repository](https://f-droid.org) will probably **not** provide the latest version in time! :hourglass_flowing_sand: 

# Related
- [Android apps section in the 36C3 wiki](https://events.ccc.de/congress/2019/wiki/index.php/Apps#Android)
- [35C3 - Official F-Droid.org repo
](https://fdroid.gitlab.io/35c3/fdroid/repo/)
- [App on F-Droid](https://f-droid.org/en/packages/info.metadude.android.congress.schedule/)
- [App on Google Play](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule)
- [App on Google Play - Beta tester channel](https://play.google.com/apps/testing/info.metadude.android.congress.schedule)
- [Issue #149: CCCamp 2019 / Deployment / F-Droid](https://github.com/EventFahrplan/EventFahrplan/issues/149)
- [Issue #80: Improve F-Droid listing](https://github.com/EventFahrplan/EventFahrplan/issues/80)
- [Issue #84: add F-Droid badge](https://github.com/EventFahrplan/EventFahrplan/pull/84)

---

/cc @Bubu @jspricke

**Comment by Bubu** [comment]
So, I'm confused again about the app, will this be an update to any previous version? Or get a new appID again? What shall we build, from where and starting when?

(Pretty sure it won't be in the official repo in time again.)

**Comment by johnjohndoe** [comment]
> ... will this be an update to any previous version?

It will be an update of the [35C3 Schedule app](https://f-droid.org/en/packages/info.metadude.android.congress.schedule/).

> Or get a new appID again?

The package name aka appID will stay the same.

> What shall we build, from where

You can pick up the [v.1.41.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.0) tag from this repository as soon as I push it.

> and starting when?

I will let you know when I push it.

> (Pretty sure it won't be in the official repo in time again.)

I still have hope. I just pushed a [minor update](https://gitlab.com/fdroid/fdroiddata/merge_requests/6091) there.

**Comment by eighthave** [comment]
I synced the description and translations, the update looks good, so it doesn't need to change every year ;-)

**Comment by johnjohndoe** [comment]
@Bubu I pushed the [v.1.41.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.0) tag. You can trigger an F-Droid build.

**Comment by Bubu** [comment]
Added to the build metadata. No idea when it will build.  Auto updates should work from now on.

**Comment by johnjohndoe** [comment]
Thanks. Will there be a separate F-Droid repository which users have to manually add similar to the ones from last Congress and Camp (linked above)?

**Comment by Bubu** [comment]
Currently working on the automation behind that.
It will be that same repo as at camp.

**Comment by Bubu** [comment]
@johnjohndoe The apps should be deployed to that repo, when I start it I get a connection failure: unknown adress, raw.githubusercontent,com. Is that to be expected at this point?

**Comment by johnjohndoe** [comment]
@Bubu I just add the repository fresh to a phone, installed and started the app without problems. To me it looks good. The failure looks as if there is missing connectivity to resolve the DNS address. The commata in `raw.githubusercontent,com` is a typo here, I guess?

**Comment by Bubu** [comment]
Working now. Knowing my ISP at home a DNS problem sounds very likely....

(Just submitted a crash report though :))

**Comment by johnjohndoe** [comment]
Nice. I updated the first post :arrow_up: in this issue and the Congress wiki.
Where is the page hosted? Can we make it a bit more beautiful similar to the [35C3 instance](https://fdroid.gitlab.io/35c3/fdroid/repo/)?

**Comment by Bubu** [comment]
>  Where is the page hosted? Can we make it a bit more beautiful similar to the 35C3 instance?

Still working on it.

**Comment by Bubu** [comment]
Done!
Please test and report any problems: https://fdroid.gitlab.io/ccc/

The repo should be able to auto-deploy updates every 15 minutes.

**Comment by johnjohndoe** [comment]
@Bubu I pushed the [v.1.41.1](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.1) tag. F-Droid already built it. Nice. Merry :christmas_tree:

**Comment by johnjohndoe** [comment]
@Bubu I pushed the [v.1.41.2](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.2) tag.

**Comment by johnjohndoe** [comment]
@Bubu I pushed the [v.1.41.3](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.3) tag.

**Comment by johnjohndoe** [comment]
@Bubu I pushed the [v.1.41.4](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.4) tag.

**Comment by johnjohndoe** [comment]
36C3 is over and I hereby declare F-Droid deployment as a big success. :tada: 
Thank you to everyone who help with this. :+1: 
I will close this issue now. :wave:

**Comment by johnjohndoe** [comment]
Post mortom :skull: I pushed the [v.1.41.5](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.5) tag.
