### ISSUE TITLE
Allow to hide sessions

### ISSUE THREAD

**Issue by htgoebel** [EventFahrplan/EventFahrplan#203]
Currently one can only select sessions positively (star, alarm, like, add to calendar).

I would like to be able to "deselect" (or hide) session, that I'm not interested in. When preparing for the day, This would allow to reduce the number of sessions in view.

**Comment by johnjohndoe** [comment]
@htgoebel Thank you for your feature request. Actually, this is one of the most interesting features for me, too. Actually, I created another issue which contains your idea and even more. See https://github.com/EventFahrplan/EventFahrplan/issues/12.

I close this issue as a duplicate. Let's continue the conversation in the linked issue.
