### ISSUE TITLE
Feature request: add feature request template for "New issue" on GitHub

### ISSUE THREAD

**Issue by CodingSpiderFox** [EventFahrplan/EventFahrplan#211]
I'm a bit confused that when I click "New Issue" on this repository, I cannot create an issue of type "Feature request" but only "Bug report" or "Crash report"

**Comment by johnjohndoe** [comment]
There is no special template for a feature request. Just use the link at the bottom to create a "blank issue" indicated in the sceenshot.

![image](https://user-images.githubusercontent.com/144518/71514267-2b9ee980-289e-11ea-96a7-068a1415cf17.png)
