### ISSUE TITLE
Feature request: auto reload after pasting personal URL from engelsystem.de

### ISSUE THREAD

**Issue by CodingSpiderFox** [EventFahrplan/EventFahrplan#212]
# How to reproduce
Paste own engelsystem JSON URL in the settings view

# Observed behavior
- went to schedule overview
- swiped to left side to see my angel shifts
- nothing there

# Expected behavior
- app loads the content in the background without any further manual interaction after pasting the URL
- when going to the event overview, it should show the data immediately

# Related
#181

**Comment by johnjohndoe** [comment]
Thanks for your feature request. I actually implemented this feature yesterday, see https://github.com/EventFahrplan/EventFahrplan/pull/209. It has been release this morning with v.1.41.2.
