### ISSUE TITLE
Support for timezones

### ISSUE THREAD

**Issue by susca** [EventFahrplan/EventFahrplan#213]
In the Fahrplan view my local time is displayed with a yellow marker. This is useful only to people in the timezone of the event, i.e. UTC+01. For everybody else, the alarms are not usable and they have to scroll down or up every time they open the app.

Please either read the current timezone from the OS or make it possible to choose an offset or the timezone.

I am not a good Java programmer, hence no MR. Thank you for your effort!

**Comment by johnjohndoe** [comment]
@susca, thank you for filing this issue. If I understand it correctly it matches what is described in issue #69. If you agree I kindly ask you to continue the discussion there and to close this issue. Thank you.

**Comment by susca** [comment]
@johnjohndoe you are right, I didn't see that issue (#69 ) . Thanks for pointing it out!

closing this one.
