### ISSUE TITLE
Newly added stages / locations don't show up

### ISSUE THREAD

**Issue by fapdash** [EventFahrplan/EventFahrplan#216]
# Environment
- App version: 1.41.1
- Android version: LineageOS 14
- Branch:
- Device: Galaxy S3

# Behavior

I don't know if I reach the people running the 36c3 Fahrplan this way, so please point me in the right direction if this is the wrong place.
We added a new Room to our pretalx today.
The sessions scheduled there show up in the "Schedule changes" changelog but I can't find the room by swiping left and right.
Tested with multiple devices.

**Comment by johnjohndoe** [comment]
Hi @fapdash. This project "only" renders the schedule data. If you need support with integrating your stage I recommend you talk to the [@c3voc people](https://twitter.com/c3voc) and maybe file an issue in https://github.com/voc/schedule. Please make sure to include a bit more context and details such as which Pretalx instance and the name of your session.

**Comment by fapdash** [comment]
@johnjohndoe Thanks, this was really valuable info. :)

Anyways, the problem was sitting in front the screen in this instance.
I was searching for a day for which there was no session scheduled for this room, so the app omits the room in the overview.

**Comment by johnjohndoe** [comment]
> I was searching for a day for which there was no session scheduled for this room, so the app omits the room in the overview.

Aah. So you added a session on another day while the app had a day open where there was no session scheduled for this room. Damn. I hope it did not take you too long to find out.
