### ISSUE TITLE
Returning from talk details to schedule view takes as much as ~4 seconds every time

### ISSUE THREAD

**Issue by hartwork** [EventFahrplan/EventFahrplan#224]
# Environment
- App version: 1.41.3
- Android version: 8.0.0
- (Branch: Google play default?)
- Device: Huawei P10 Lite

# How to reproduce
Thanks for developing this app and sharing it as software libre! :+1: 

1. Open app, starts in table schedule view
2. Click any single talk, loads talk detail view
3. Press device "<" (back/escape) button to go back to table view

# Observed behavior
From press of the button it takes as much as ~4 seconds to return to the schedule view. (My device does *not* feel slow in general.) Initially, the impression of "nothing happening" made me press the button multiple times (which ends up closing the app by mistake). Once I learned it takes time, it just turns my use of the app into a waiting game — in a way "the app controls me" instead of me controlling the app. That's a bid sad.

# Expected behavior
I would hope, that going "back in time", returning to the previous view would be instant, i.e. take ~300ms rather than multiple seconds.

**Comment by johnjohndoe** [comment]
@hartwork Thank you for the feedback. Actually, there is an open issue for this behavior. Please follow-up in #108. I close this issue as a duplicate.
