### ISSUE TITLE
stalls after multiple hours.

### ISSUE THREAD

**Issue by JPRuehmann** [EventFahrplan/EventFahrplan#226]
# Environment
- App version: 1.41.3
- Android version: 9
- Branch:
- Device: Nokia3

# How to reproduce
1. Ordered list of steps
Use normaly with autoupdate.
2. to reproduce
3. the issue

# Observed behavior
- What happened?
App goes slower from Update to Update
- Add screenshot(s).
The only Way is to delete all App data and Cache and forcly close the app. Than it works again for some hours. But everytime all favourites and alarms get lost.
# Expected behavior
- What should happen?
Work normaly.

# Related
- Link to related issues here if applicable.

**Comment by johnjohndoe** [comment]
@JPRuehmann Thank you for the feedback. Actually, there is an open issue for this behavior. Please follow-up in #108. I close this issue as a duplicate.
