### ISSUE TITLE
Favorite items with yellow background are difficult to read

### ISSUE THREAD

**Issue by alberanid** [EventFahrplan/EventFahrplan#24]
Hi,
in version 1.33.1, events with a yellow-ish background become hard to read, when added to favorites (white text on a bright yellow background).
Items in all other colors are easy to read.

See the attachment; I'm using a Nexus 5x.

![image](https://user-images.githubusercontent.com/222857/34265922-c4133330-e677-11e7-8220-fead02eb7810.png)

**Comment by alberanid** [comment]
I guess that's related to #20 :-)

**Comment by johnjohndoe** [comment]
True. I missed that one. I am going to fix this in the next version.
