### ISSUE TITLE
potential memory leak of "instance" Activity variable

### ISSUE THREAD

**Issue by yuchi1989** [EventFahrplan/EventFahrplan#248]
Hi,

We (@yuchi1989 + @guitard0g) are researchers in Columbia University developing a static analysis tool to analyze memory leak bugs related to UI objects. Our tool identifies one bug in your source code (particularly the onCreate method of schedule/MainActivity.java). Here is the code snippet.

https://github.com/EventFahrplan/EventFahrplan/blob/edc70c489a5b69bfd57ed5c1fe645c436967ca43/app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java#L102

Here we are storing an Activity in a static variable, which can lead to this Activity persisting beyond its lifecycle when the app is suspended or closed. Often you can save memory usage by setting this `instance` variable to `null` in the `onPause()` or `onDestroy()` methods in the Activity.

**Comment by johnjohndoe** [comment]
Hi @yuchi1989. Thank you for pointing out this issue.

I am already aware of the implications of these static references. The code base is rather old as you can see from the commit history. I am currently in the process of reworking it. Once aspect of it will be to get rid of these static references. If you are interested you can follow along in issues like #246. I am trying to make the next steps as transparent as possible.

I will close the issue for now. Thank you again.
