### ISSUE TITLE
Publish DiVOC app in Fdroid

### ISSUE THREAD

**Issue by jugendhacker** [EventFahrplan/EventFahrplan#261]
I already open a PR on their metadata repo to publish it there, but they want you to confirm that it's okay for you if the app is published there. You can find the PR here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6607

Maybe you could leave a comment there....

**Comment by johnjohndoe** [comment]
:heavy_check_mark: I left a comment there.

**Comment by johnjohndoe** [comment]
:shipit: Available via [https://apt.izzysoft.de/fdroid](https://apt.izzysoft.de/fdroid/index/apk/info.metadude.android.divoc.schedule).

**Comment by johnjohndoe** [comment]
I guess this can be closed now. Okay @jugendhacker?

**Comment by jugendhacker** [comment]
Yes it can be closed...
