### ISSUE TITLE
Single room schedule does not expand to full with in portrait mode

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#278]
# Environment
- Affected app versions:
  - [v.1.43.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.43.0)
  - [v.1.43.1](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.43.1)
- Broken since commit: 75da59ec6c65592af02a14f93cec6c00656731fe
- Android version: Android 10
- Branch: `master`
- Device: Pixel 10

# How to reproduce
1. Install the app pointing to a _schedule.xml_ which contains sessions in **one room** only.
2. Launch the app in portrait mode.

# Observed behavior
- The horizontal extent of session views is limited.
![The horizontal extent of session views is limited](https://user-images.githubusercontent.com/144518/82941557-d8d57500-9f96-11ea-8f0a-9dc8cbaa9541.png)

# Expected behavior
- Session views expand to the **full width** of the screen.
![Session views expand to the full width of the screen](https://user-images.githubusercontent.com/144518/82941628-f6a2da00-9f96-11ea-81eb-2de7a73d765a.png)

# Related
- [Issue #263: Faster navigate back from event detail to schedule view](https://github.com/EventFahrplan/EventFahrplan/pull/263)

**Comment by johnjohndoe** [comment]
@ideadapt fyi

**Comment by cketti** [comment]
This might be fixed by #277

**Comment by johnjohndoe** [comment]
@cketti No, the bug is still present on your branch at this state.

**Comment by cketti** [comment]
Yeah, nevermind. It's a layout issue. `HorizontalSnapScrollView` has a `layout_width` value of `wrap_content`.
