### ISSUE TITLE
Search / filtering functionality

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#3]
@sedrubal [wrote](https://github.com/tuxmobil/CampFahrplan/issues/116):

> A search and filtering functionality would be useful ;)

**Comment by torantal** [comment]
Still consider this a very basic function.

"Hey, did you know there's a talk by starbug today?" "Really? Great, let me check it out and set a reminder ...

<Realise I can't search, although I have all the data in the app>

<Search in the online Fahrplan and finally find the talk, switch to the app and favourite it.>

Room for improvement... ;)

**Comment by johnjohndoe** [comment]
One more filter criteria requested by a user:
- Filter by language

**Comment by torantal** [comment]
One year later, 36c3 coming up, still searching for search... :) 

Interface-wise I would suggest the view as for favourites and a simple full text search box and the list gets populated with every hour. Perhaps some basic sorting - timeline, appearances, speaker, title.

**Comment by johnjohndoe** [comment]
@torantal True. At this point time it is still a matter of resources. I am driving this project on my own, [unpaid](https://github.com/sponsors/johnjohndoe) and in my free time. I have to prioritize the work. I am trying to [make transparent](https://github.com/EventFahrplan/EventFahrplan/milestones?state=closed) what I work on to let people follow along.

Nevertheless, I appreciate you interest in the project. If you want to sketch out a possible implementation or design then this is a very valuable contribution to the project.

**Comment by torantal** [comment]
If an interface mockup would help I'd be happy to sketch something out.

**Comment by johnjohndoe** [comment]
Visuals drafts are always helpful. It might attract others to work on this issue.

In this context I think it would make sense to reconsider how and where to put all the toolbar items in generell when adding such a think as search and filters. A bottom navigation or a floating action button come to my mind but I have not thought through which idea leads to a good user experience. If a redesign is needed in order to implement search/filter we can split the task in smaller issues. For now this issue can be used to discuss ideas.

**Comment by johnjohndoe** [comment]
# Search concept v1

The following mockups present the first concept for a search functionality implementation.

_The screens are not pixel perfect. The implementation may vary in certain details._

![Search concept v1](https://github.com/user-attachments/assets/6594469a-2967-4104-a72d-c45e1c110963)

## 1.1 Schedule screen, menu closed & 1.2 Schedule screen, menu open
- The toolbar contains a "Search" menu item which leads to the search screen.
- The search screen opens as a full screen on smartphones and as a sidepane view on tablets.

## 1.3 Initial empty search screen
- The search screen opens with an empty state initially.
- The empty state illustration is shown with some guiding text.
- A full text search allows to search through all session properties.
- Navigating to the previous screen works via the back gesture.

## 1.4 Search history
- If previous searches have been performed recent searches are shown when opening the search screen.
- Up to 20 search queries are remembered.
- The latest search query is shown on top.
- Tapping a history item results in that search query being used in the input field.
- Recent searches can be cleared to protect users' privacy.
- Navigating to the previous screen works via the back gesture.

## 1.5 Search results
- Search results are show immediately while typing.
- A search result shows the date/time, title and speakers.
- Navigating to the details screen works by tapping an item.
- The search query can be discarded by tapping the `x` symbol.
- Navigating to the previous screen works by tapping the arrow-left icon or via the back gesture.

## 1.6 No search results
- The empty state illustration is shown with some guiding text.
- The search query can be discarded by tapping the `x` symbol.
- Navigating to the previous screen works by tapping the arrow-left icon or via the back gesture.

**Comment by johnjohndoe** [comment]
# Search concept v2

The following mockups and notes are rough ideas of potential future implementations.

_The screens are not pixel perfect. The implementation may vary in certain details._

![Search concept v2](https://github.com/user-attachments/assets/d158ce99-b7c2-4ef0-b432-65d8c7b81b05)

## 2.1 Scoped search
- The search query can be entered but does not trigger a search result immediately.
- Once can tap one of the scope items to narrow down which session properties are searched through.
- Tapping the magnifier icon in the soft-keyboard executes the default search: all texts.

## 2.2 Show results in schedule screen & 2.3 Schedule screen filtered
- In addition to 1.5 an interaction element is shown which allows to show the results in the schedule screen.
- The schedule screen shows the usual tabular layout but only the rooms and session which match the search result.
- An interaction element is shown to reset the search results to show the full schedule again.

## Rough ideas
- Subscribe to search and get notified when a new session appears or an existing is updated which matches the search query
- Split search query by space, evaluate as `AND`; use quotes to evaluate as a single term with spaces
- Evaluate using [chips](https://m3.material.io/components/chips/overview)
- Filter by "being recorded" state
