### ISSUE TITLE
Self Organized Sessions?

### ISSUE THREAD

**Issue by rumgewieselt** [EventFahrplan/EventFahrplan#31]
Is it possible to integrate Self organized Sesions? 
Thanks for your effort. 

BR

**Comment by johnjohndoe** [comment]
I am currently working on it. I had to wait for the C3VOC to provide the wiki export. Please sign up as a **beta tester** in [Google Play](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule) to receive the app earlier.

**Comment by johnjohndoe** [comment]
Beta version is rolling out now!

**Comment by knobhead** [comment]
Hmm, where did this feature go? 🤔
Any way to — scriptedly — combine fahrplan schedule and SOS wiki export to a common xml?

**Comment by johnjohndoe** [comment]
@knobhead The _Self Organized Sessions_ are contained in the current version of the [35c3 Schedule app for Android v.1.38.0](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule). In any case the @voc maintains the aggregation of the schedule data. If you have any issue with the content aka. schedule data please file reach out to the @voc in [this issue tracker](https://github.com/voc/schedule/issues).
