### ISSUE TITLE
Complete Swedish translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#325]
It would be nice to have a Swedish translation of the app. :sweden:  

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [ ] Update or add new translations in `app/src/main/res/values-sv`
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left
  - Take `app/src/main/res/values` (English) as a reference.
  - Ignore strings with the `translatable="false"` attribute and `placeholder` strings.
  - Files to cover: `preferences.xml`, `strings.xml`
  - Do not modify, commit files outside of the `-sv` folder.
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Ensure that `plurals` are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [ ] Optional: Add new translations in `app/src/rc3/res/values-sv` (becomes visible when you change the _Build Variant_)
- [ ] Optional: Add new translations in `app/src/ccc36c3/res/values-sv` (becomes visible when you change the _Build Variant_)
- [ ] Optional: Add new translations in `app/src/cccamp2019/res/values-sv` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by frangiz** [comment]
I can give this one a try. Just need to figure out how to find the Translations Editor on a new install of Android Studio.

**Comment by johnjohndoe** [comment]
@frangiz Cool. Please let me know if you need assistance. You can also edit the files in any plain text editor such as Vi or Sublime Text. But it won't be as comfortable.

**Comment by johnjohndoe** [comment]
Translations are now managed on Crowdin. See #551.
