### ISSUE TITLE
Add Japanese translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#326]
It would be nice to have a Japanese translation of the app. :jp:   

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [x] Add new translations in `app/src/main/res/values-ja` (ignore `placeholder` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left
  - Files to cover: `preferences.xml`, `strings.xml`
  - Do not modify, commit files outside of the `-ja` folder.
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Ensure that [`plurals`](https://developer.android.com/guide/topics/resources/string-resource#Plurals) are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
- [x] Optional: Add new translations in `app/src/ccc36c3/res/values-ja` (becomes visible when you change the _Build Variant_)
- [x] Optional: Add new translations in `app/src/cccamp2019/res/values-ja` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by hiennghiem** [comment]
I like to work on this. Please assign it to me! :D

**Comment by hiennghiem** [comment]
Hi there,
I've finished translating strings.xml using Translation Editor.
![Screen Shot 2020-10-04 at 08 44 04 AM](https://user-images.githubusercontent.com/30136208/95005084-cdb5e400-061d-11eb-81e2-398afe033969.png)


But it seems that I can't do the same with preferences.xml (there's no option for opening it with Translation Editor)
![Screen Shot 2020-10-04 at 08 40 20 AM](https://user-images.githubusercontent.com/30136208/95005097-f9d16500-061d-11eb-8cf6-bfc5d72b1827.png)

So I assume that I could copy preferences.xml from `app/src/main/res/values` , paste into `app/src/main/res/values-ja`
 and directly translate on that file.
Is that ok? If not, please guide the right way.

(Sorry for I'm quite new to Android studio)

**Comment by johnjohndoe** [comment]
It seems you identified to be a weakness of Android Studio. :disappointed: It does not automatically create a `values-ja/preferences.xml` file when one adds Japanese as a new language.
I would do the following: Copy `values-de/preferences.xml` to `values-ja/preferences.xml`, and then open the `Translation Editor`. It shows all strings both from `strings.xml` and `preferences.xml`. I recommend to copy the German file because the English contains non-translatable strings which you would copy with it.

**Comment by hiennghiem** [comment]
I've just created the PR for this issue. Hope it might help.
https://github.com/EventFahrplan/EventFahrplan/pull/334
