### ISSUE TITLE
Complete and update Russian translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#328]
Review, complete and update existing Russian translations of the app. :ru: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the **missing** translations as shown in the screenshot. Existing translations might be **outdated** or **incomplete** and must be checked critically.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [ ] Review, complete and update existing translations in `app/src/main/res/values-ru`
  - Take `app/src/main/res/values` (English) as a reference.
  - Ignore strings with the `translatable="false"` attribute and `placeholder` strings.
  - Do not modify, commit files outside of the `-ru` folder.
  - Files to cover: `preferences.xml`, `strings.xml`
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Ensure that `plurals` are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [ ] Complete and update translations in `app/src/rc3/res/values-ru` (becomes visible when you change the _Build Variant_)
- [ ] Complete and update translations in `app/src/ccc36c3/res/values-ru` (becomes visible when you change the _Build Variant_)
- [ ] Complete and update translations in `app/src/cccamp2019/res/values-ru` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by rizabek-mukanov** [comment]
@johnjohndoe , I am english/russian speaker, but I do not have any android development experience, is it required to complete translations?
I was hoping I will open translation editor, which is on your screenshot, and fill all missing fields for russian language and that will be enough.

**Comment by johnjohndoe** [comment]
@rizabek-mukanov Android development is not a requirement. There are a few XML attributes (`xliff`) which need to be kept in the file but please give it a try. If you get lost on the way I am happy to help out.

**Comment by rizabek-mukanov** [comment]
@johnjohndoe , sounds good. let's try

**Comment by rizabek-mukanov** [comment]
@johnjohndoe , can you please take a look at [this commit](https://github.com/rizabek-mukanov/EventFahrplan/commit/76d559c1c2afbfc3b8ee8925be692d57f861c786) just to make sure I did it correct. Once confirmed, I will continue. 
and couple questions.
1. I suggest making Osprey not translatable, since it is device name. I suppose you named it after bird?
2. is  Leipziger Messe a fair? where people sell different things? just making sure I translated correctly
Thanks

**Comment by johnjohndoe** [comment]
I left some comments there - basically stating that you should only change/commit files which relate to the Russian translation and do not translate `placeholder` strings as mentioned above. With regards to your questions:

1. What are Osprey are your referring to?
2. It is just the location of the event. There are various fairs happening. It would okay to translate it as "fair" but it would also okay to keep the German name because this is what everybody would watch out for then they visit the event in person.

**Comment by johnjohndoe** [comment]
@rizabek-mukanov Did you have time to work on the translation? You can start a pull request at any time and we can make it perfect together.

**Comment by johnjohndoe** [comment]
@rizabek-mukanov Can you please state if you will work on this? If you do not have time I like to offer the issue to somebody else.

**Comment by rizabek-mukanov** [comment]
@johnjohndoe , hello. sorry, completely forgot about this, was busy at job. If i complete this on weekend, will that work for you?

**Comment by johnjohndoe** [comment]
Translations are now managed on Crowdin. See #551.
