### ISSUE TITLE
Complete and update Portuguese translation (10/2020)

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#329]
Review, complete and update existing Portuguese translations of the app. :portugal: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the **missing** translations as shown in the screenshot. Existing translations might be **outdated** or **incomplete** and must be checked critically.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [ ] Review, complete and update existing translations in `app/src/main/res/values-pt` (ignore `placeholder` strings)
  - Files to cover: `preferences.xml`, `strings.xml`
  - Do not modify, commit files outside of the `-pt` folder.
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Ensure that [`plurals`](https://developer.android.com/guide/topics/resources/string-resource#Plurals) are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
- [ ] Complete and update translations in `app/src/ccc36c3/res/values-pt` (becomes visible when you change the _Build Variant_)
- [ ] Complete and update translations in `app/src/cccamp2019/res/values-pt` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by larissayasin** [comment]
I like to work on this

**Comment by romeroclaudino** [comment]
Hey there @larissayasin and @johnjohndoe! I can help you with the translation if you need it. I'm a Brazilian, therefore, I'm also a native Portuguese speaker. I also have experience in developing android applications.

**Comment by johnjohndoe** [comment]
Hi @larissayasin and @romeroclaudino. Thank you for offering your help. I ask myself if it makes sense to have a Portuguese and a Brazilian translation. I can not tell myself if they would differ a lot. The existing translation has been made by people from Brazil. What do you think?

**Comment by larissayasin** [comment]
I'm Brazilian too. It is more common to see brazilian portuguese translations in softwares anyway. I think I never saw a software with 2 Portuguese translations.

**Comment by johnjohndoe** [comment]
Ah great. For me it is fine if you "only" work on the `-pt` files then. As a procedure I propose that @larissayasin starts with the translation and @romeroclaudino reviews her result as a language quality check (which I cannot do).

**Comment by romeroclaudino** [comment]
Hey there!
I'm sorry guys, I have had some pretty busy days lately...
Sure @johnjohndoe! I can review it and I'm gonna do it today.

Also, I'm a participant at the Hacktoberfest and I was looking forward to contribute with at least one pull request.
The translation was complete done by @larissayasin or there's something left that allows me to create another one?

If she did that's wonderful. I could still translate your README file if you want me to. Let me know what you think about it.

**Comment by johnjohndoe** [comment]
> I could still translate your README file if you want me to. Let me know what you think about it.

Thanks for the offer. I don't want the README to be translated. English is a requirement for development on this project.
I might however have some another pull request later on.

If you are up for more you could jump over to [another project of mine](https://github.com/Umweltzone/Umweltzone) and add a Portuguese translation. Let me know if you need an issue there or if the information in one of the other translation issues is sufficient.

**Comment by romeroclaudino** [comment]
That would be wonderful @johnjohndoe!
I would appreciate if you could create the issue.

**Comment by johnjohndoe** [comment]
@romeroclaudino Here you go: https://github.com/Umweltzone/Umweltzone/issues/81

**Comment by johnjohndoe** [comment]
@larissayasin If you also want to help there you could split the work - one could do the FAQs.
