### ISSUE TITLE
Misplaced resp. multiple time column highlights

### ISSUE THREAD

**Issue by torantal** [EventFahrplan/EventFahrplan#33]
Day 2 of 34c3. 0:10 28.12

The current time highlighted is at the end of day 2 instead of the start

Actually it should highlight at the end of day 1

# Hints
- The original schedule data of the `34C3` event can be requested from @johnjohndoe to analyze this issue.

# Related
- [Issue #105: Current time marker](https://github.com/EventFahrplan/EventFahrplan/issues/105)
- [Issue #167: Time column not shown](https://github.com/EventFahrplan/EventFahrplan/issues/167)

**Comment by pseyfert** [comment]
Expanding on this, the time highlight even appears twice on day 2. Once at the top, and once at the bottom. (System time was set for 0.31 in the night from day 1 to day 2, i.e. just before Nico's talk, but the highlighter suggests Martin is talking)

![screenshot_20181228-003122](https://user-images.githubusercontent.com/5124749/50640894-87be7e80-0f66-11e9-9d9e-e38b877deb11.png)
![screenshot_20181228-003132](https://user-images.githubusercontent.com/5124749/50640895-87be7e80-0f66-11e9-8569-d09886006faa.png)
![screenshot_20181228-003139](https://user-images.githubusercontent.com/5124749/50640896-88571500-0f66-11e9-9f51-d7171ef6a612.png)
