### ISSUE TITLE
Fahrplan for rC3 

### ISSUE THREAD

**Issue by kinafu** [EventFahrplan/EventFahrplan#353]
To use the 36c3 Fahrplan App with the current data (rC3), manually change the schedule URL to the [URL given on this page](https://links.rc3.io/#android-apps-schedule).

(I just created the issue for others looking for the rC3 Fahrplan app or how to use the Fahrplan app with rC3. 
The issue can be dismissed when the rC3 is over.)

**Comment by johnjohndoe** [comment]
Thank you. But there is actually a dedicated version of the app which can be found here: https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.48.0

**Comment by kinafu** [comment]
I only looked up [F-Droid](https://search.f-droid.org/?q=fahrplan&lang=de) and [Google Play Store](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule) to check for a dedicated update for your Fahrplan app.
Thanks for already publishing a new version for the rC3 😄.

**Comment by johnjohndoe** [comment]
Not your fault. It is just that Google and F-Droid did not process the apps to have it available on time. Still not :(
It is about time for somebody to set up a dedicated F-Droid repository such as https://fdroid.gitlab.io/ccc/ (not usable at the moment).

**Comment by johnjohndoe** [comment]
Google Play published version 1.48.0 today.
Meanwhile, there is an update available here: https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.48.1

**Comment by johnjohndoe** [comment]
Looks like [Google Play](https://play.google.com/store/apps/details?id=info.metadude.android.rc3.schedule) is :racing_car: fast today. Version 1.48.1 is available there, too.

**Comment by johnjohndoe** [comment]
Final last words, At 31.12.2020 the app also [appeared on F-Droid](https://f-droid.org/en/packages/info.metadude.android.rc3.schedule/) (first rC3 release) - too late, though :disappointed:.
