### ISSUE TITLE
Missing spaces if returns are not used (plus a null at the beginning) when sharing a text

### ISSUE THREAD

**Issue by joergi** [EventFahrplan/EventFahrplan#354]
# Environment
- App version: 1.48.0
- Android version: Android 10
- Branch: Master
- Device: Faiphone 3+

# How to reproduce
1. go into event
2. press share button (as text)
3. share with an app, which is not using `\n` or `\r` ( I use [Social Slim for Twitter](https://f-droid.org/de/packages/it.rignanese.leo.slimtwitter/), an Twitter Client from F-Droid)
3. there is a text, with no spaces and `(null)` at the beginning (see screenshot)

# Observed behavior
- null at the beginning.
- missing spaces
![grafik](https://user-images.githubusercontent.com/1439809/103229533-8052c580-4933-11eb-93b5-418e1b87824d.png)

![grafik](https://user-images.githubusercontent.com/1439809/103228953-4634f400-4932-11eb-861e-62f452341e75.png)

# Expected behavior
- extra spaces before each `\n`  or `\r`
- no null at the beginning

**Comment by cketti** [comment]
In my opinion it should be up to the app that ignores line breaks to take measures so the text remains readable.

Looking at the code I don't think the "null" string comes from the EventFahrplan app. It's probably an issue with the target app.

**Comment by cketti** [comment]
This needs to be fixed here: https://github.com/rignaneseleo/SlimSocial-for-Twitter/blob/32dcd115f5e66e7a996edd351a4b81ca09781e22/SlimTwitter/app/src/main/java/it/rignanese/leo/slimtwitter/MainActivity.java#L94-L122

**Comment by joergi** [comment]
@cketti + @johnjohndoe - the last release of the slim social app is from 2017 - the last commit to the default branch from 2018.

I understand, that the problem is not in the Fahrplan app.

So, does it make sense, to add it anyway?
a space before a return will not hurt anyway.

**Comment by joergi** [comment]
I got info from @RignaneseLeo that [he will update the SilmSocial for Twitter,](https://twitter.com/RignaneseLeo/status/1343662817761701889) I will have a look if I can update it 
Related issue: https://github.com/rignaneseleo/SlimSocial-for-Twitter/issues/19

**Comment by johnjohndoe** [comment]
@joergi Has this been resolved in the other app?

**Comment by cketti** [comment]
The bug in SlimSocial for Twitter hasn't been fixed yet. But there's a PR now: https://github.com/rignaneseleo/SlimSocial-for-Twitter/pull/20

I see no reason why such a bug in another app should be worked around in EventFahrplan. I'd close this issue.

**Comment by joergi** [comment]
Thanks @cketti 
I would suggest the same @johnjohndoe.
