### ISSUE TITLE
Add loading state to favorites screen

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#412]
> There's no loading state. When loading the list takes some time the empty view ("No favorite lectures") is displayed.

_Originally posted by @cketti in https://github.com/EventFahrplan/EventFahrplan/pull/404#pullrequestreview-781050635_

**Comment by Chase22** [comment]
I like to work on this

I will first get to know the app and the codebase, so i might end up doing #411 first

**Comment by johnjohndoe** [comment]
@Chase22 Welcome :wave: That would be great. Please share your ideas here how you would realize that so we can discuss them before you start coding.

**Comment by Chase22** [comment]
An excellent idea and one that i should have thought about before starting. So my basic idea:

I want to add a new overlay (Possibly ConstraintLayout) to the [StarredListFragment](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt) with an Android Progress Bar. I can add text but i don't think it's necessary and just adds a lot of extra effort for translating.

This view will be shown by default and hide the ListView behind it. Then when we get a new dataset from the ViewModel, the visibility is set to gone, hiding the screen. This happens as soon as the data is loaded for the first time.
https://github.com/EventFahrplan/EventFahrplan/blob/8ceb735c7e54015f70e124f6aedb03ad8172332b/app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt#L124-L141

I think it's a pretty simple way of implementing it without having to go deeper into the structure of the Views and Fragments

**Comment by johnjohndoe** [comment]
That sounds good to me. Please mind that there is also an **empty view** if no favorites have been selected. That should not hinder you though - you just need to manage the visibility of each. I guess you want to use a **progress spinner** - that should fit. 

Hint: On the data level (`AppRepository`) currently you might be missing a **loading state** to be emitted into the `Flow`. You will have to add that and probably introduce a `Result` wrapper. Please have the other screens in mind so we are able to apply a similar pattern there.

**Comment by Chase22** [comment]
The progress bar actually includes the spinner function. 

On the loading state level given that we are using flows we don't actually need an explicit loading state. The flow gets triggers at view creation and an indeterminate time later the observer gets triggered to hide the loading spinner. 

This is also independent from the actual returned values of the query. If no starred talks are found the observer gets triggered with an empty list, in which case the loading spinner still gets hidden.

**Comment by johnjohndoe** [comment]
Sounds good. Please give it a try.

**Comment by Chase22** [comment]
Implementation is done so far, i will open the PR when i'm back home this evening and can test the feature on android 4.1
