### ISSUE TITLE
Stay at current scroll position when going back from event details view

### ISSUE THREAD

**Issue by MaxValue** [EventFahrplan/EventFahrplan#42]
It is really beneficial for the normal user workflow to stay at the current scroll position.

At the moment, the app **always scrolls back to the current time** and the user has to scroll all the way down again.

Many users go through the schedule and try to decide which lectures/talks to go to.

# Enviroment

- Device vendor: Lenovo/ZUK
- Device model: [ZUK Z1](https://www.gsmarena.com/lenovo_zuk_z1-7511.php) (Smartphone)
- Android version: 5.1.1
- Cyanogen version: 12.1-YOG4PAS9IG
- App version: 1.33.1

# How to reproduce
1. Start the app, navigate to the main view (if necessary)
2. Scroll up or down and tap on a talk to see it's details.
3. Tap the back-button.
4. You are now at the current time again, not where you initially scrolled to.

# Also the following Developer Options were customized
- Window Animation Scale: Off
- Transition Animation Scale: Off
- Animation Duration Scale: Off

**Comment by johnjohndoe** [comment]
Thank you for reporting the issue. Can you please provide additional information such as what exactly you do to reproduce the error and which device, Android version, app version you use? Please edit your text above.

**Comment by MaxValue** [comment]
Updated :)

**Comment by johnjohndoe** [comment]
I noticed that the position to which the schedule view is scrolled to depends on a few more factors:

### Scenario 1: The day is today and portrait mode
- Scrolls to the time block of the current time

### Scenario 2: The day is today and landscape mode
- Scrolls to the top of the column

### Scenario 3: The day is not today and portrait or landscape mode
- Scrolls position is as before
