### ISSUE TITLE
Complete and update Spanish translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#427]
It would be nice to have a complete Spanish translation of the app. :es: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the **missing** translations as shown in the screenshot. Existing translations might be **outdated** or **incomplete** and must be checked critically.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/146167475-5b4a149d-aafb-43b4-aca6-788a75f7e6ea.png)

Please use the automatic formatting for the string files which Android Studio provides.

- [ ] Review, complete and update existing translations in `app/src/main/res/values-es`
  - Files to cover: `preferences.xml`, `strings.xml`.
  - Take `app/src/main/res/values` (English) as a reference.
  - Ignore strings with the `translatable="false"` attribute and `placeholder` strings.
  - Adapt the date format in `app_hardcoded_subtitle` to the country.
  - Do not modify, commit files outside of the `-es` folder.
  - Ensure that [`plurals`](https://developer.android.com/guide/topics/resources/string-resource#Plurals) are covered (`schedule_changes_dialog_number_of_sessions`, `schedule_changes_dialog_being`, `notifications_schedule_changes`). The _Translation Editor_ might not point them out.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [ ] Complete and update translations in `app/src/rc3/res/values-es` (becomes visible when you change the _Build Variant_)
- [ ] Complete and update translations in `app/src/ccc36c3/res/values-es` (becomes visible when you change the _Build Variant_)
- [ ] Add new translations in `app/src/cccamp2019/res/values-es` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- Please read the [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before you start working.

---

:hand: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by Delawen** [comment]
Is there any other tool that is not Android Studio to do this?

Thinking on some tools like https://www.transifex.com/

**Comment by johnjohndoe** [comment]
I haven't set up Transifex or alternatives yet. You can edit the respective files with a **plain text editor** (Sublime Text, ...), though - if you prefer. You will need to compare with another **complete** language, e.g. German or Polish.

**Comment by matmair** [comment]
@johnjohndoe would you be ok with crowdin as a translation service? I set it up on a few FOSS projects before and would be happy to create a PR.
Crowdin provides a nice way to have a single PR you can merge back in once you want to update (so you can have a string-change freeze for all the translators to finish) and has build in translations so common translations are recommended.
Loved your rc3 talk.

**Comment by johnjohndoe** [comment]
@matmair Thank you for the initiative. I have **not** compared [Transifex](https://www.transifex.com), [Weblate](https://weblate.org), [Crowdin](https://crowdin.com), ... yet. If you have experience with Crowdin, believe it fits ([restrictions of the free plan](https://crowdin.com/pricing#crowdin-pricing-key-features)) with the project and want to set it up then that would be great. :+1: Do you have plans to manage translations for longer for this project?

:phone: If you think it is helpful we can talk in person at some point. Just contact me via email. :envelope:

**Comment by matmair** [comment]
@johnjohndoe I do not really have a preference for either Crowdin or Transifex, I just find Crowdin to be a lower maintenance community - but that could be down to projects I work on/with.
Crowdin provides open-source projects with a free pro version and I use that with other projects.

My language selection is somewhat limited, I can do Austrian, German, English, a bit of French if pressured. But I would totally be willing to Shepard it as I have to visit Crowdin on a regular basis for other projects. It is not that time-intensive in my experience.

I set up a sample project so you can get a feel for the solution:
https://crowdin.com/project/eventplan
If you like it you would have to create an account for it as it uses an OAuth flow to sync to Github (and also so I can not run away with your precious translations). You can - if you want to - make me a manager or proofreader (no access to project settings) then I can finish the setup / submit a PR with the required settings file for the repo, upload all existing translations etc.

**Comment by Delawen** [comment]
I have some spare hours I can use to translate to Spanish. But if I have to manage the files manually, those hours will not do much. That's why I asked if there's any tool.

I haven't used crowdin, but it looks like something I can work with. So +1 to that.

**Comment by johnjohndoe** [comment]
Thanks @matmair and @Delawen for your commitment. As soon as I have a bit of time I will jump in here. Please be patient with me.

**Comment by matmair** [comment]
@johnjohndoe no hurries, it is a hobby after all😇.
@Delawen if you have time and want to you can use the linked test instance to translate. The translations get merged into the master_l10n branch of my fork. Either you or I can submit the diff to upstream, however you like. If I should submit a PR just ping me!

**Comment by matmair** [comment]
@johnjohndoe kingu are right about their observations, all named tools have their own unique upsides.

The main reason I like Crowdin is that their interface is changing in nice small steps and everything is simple. If you translate you only need 2 views: the project overview to see how much of each language is done and the editor. There are filters, autotranslations, discussions, approved strings and old strings. That is all you need. It does not get a lot more complex for the admin.
While there are many tools I like simple ones - while retaining the possibility to have a firewall against misuse (the approval step).

**Comment by johnjohndoe** [comment]
> I set up a sample project so you can get a feel for the solution: https://crowdin.com/project/eventplan If you like it you would have to create an account for it as it uses an OAuth flow to sync to Github (and also so I can not run away with your precious translations). You can - if you want to - make me a manager or proofreader (no access to project settings) then I can finish the setup / submit a PR with the required settings file for the repo, upload all existing translations etc.

I created [a Crowdin project](https://crowdin.com/project/eventfahrplan) a few days ago and invited @matmair to it. Once you have time please check if the setup makes sense and if the trial plan is good or if I picked something wrong.

**Comment by matmair** [comment]
@johnjohndoe the strings are imported and ready - now it only needs translating beings 😇.
@Delawen the platform is [live now](https://crowdin.com/project/eventfahrplan). If you or anyone of the FOSS4G community (thanks for the effort there!) want, I will clear(approve all issues/translation at least weekly.

**Comment by johnjohndoe** [comment]
:bellhop_bell: I created a discussion thread for general purpose topics. Please continue in #464 if anything comes up.

**Comment by johnjohndoe** [comment]
Translations are now managed on Crowdin. See #551.
