### ISSUE TITLE
Move DetailBar out of Scroll View

### ISSUE THREAD

**Issue by isiko** [EventFahrplan/EventFahrplan#440]
At the moment, the Detail Bar is inside the ScrollView, so depending on the ScrollBar style, it is either sometimes covered by the ScrollBar, or there is a relatively awkward gap where the padding for the ScrollBar is.

## Using an Inset
<img src="https://user-images.githubusercontent.com/44641688/149623445-f104a6c6-8a17-43a1-84de-a0f3e67670b3.png" alt="inset" width="200"/>

## As anOverlay
(I colored the ScrollBar Green for better Visibility)
<img src="https://user-images.githubusercontent.com/44641688/149623463-a306b951-736d-4cbd-a20d-3f611136203c.png" alt="overlay" width="200"/>

A relatively simple fix would be to get the DetailBar out of the ScrollView so that it is always displayed above the ScrollView. This way it is possible that ScrollBar and DetailBar do not interfere with each other.

**Comment by isiko** [comment]
Also, I would work on this

**Comment by johnjohndoe** [comment]
In the `rC3` build flavor the background of the whole screen is dark. The scroll bar color is some transparent white value. Thereby, both the background as well as the DetailBar shine through. I kind of like this transparency effect. Of course this does not work with white on white - but would be fixed once #441 is done.

The DetailBar itself does not contain too important information - in my opinion - to be shown permanently when the user scrolls down. It would occupy horizontal space which could be used to show the text description instead. I am not sure if it's worth a rewrite. If you still want to test it I am happy to take a look. No promises, though.

Related: please note that there is an open discussion on how to redesign the layout of the details screen triggered by #231 and #227.

**Comment by isiko** [comment]
I actually haven't thought about these effects but I also think that something like this would be a cool effect to keep. My only problem is that if the width of the ScrollBar is set too high, part of the EventID is obscured, which is probably not intentional. This should probably be included in #441, but perhaps it would be helpful to put some padding on the right side of the padding and use the width of the ScrollBar as the width of the padding. This would result in an effect similar to the `insideInset` scrollBar style, but with the detailBar still spanning the entire screen and not having an unsightly gap where the ScrollBar would go.

**Comment by johnjohndoe** [comment]
I agree that it does makes sense to relate the values (width of the scrollbar and padding of the detailbar) to **protect** the layout from customization done by some developer. In this case I suggest applying the value **both** to the left and the right side to keep the padding of the detailbar **symmetric**. Please note that the date text in the detailbar **horizontally aligns** with the texts (title, abstract, description, ...) in the session.

Further, I would not change the **current width value** of the scrollbar at the moment.
