### ISSUE TITLE
Add custom ScrollBar

### ISSUE THREAD

**Issue by isiko** [EventFahrplan/EventFahrplan#441]
Currently the ScrollBar is just a transparent rectangle on the side of the screen. It would be cool to be able to change the color of it or to add round edges.

Also, as mentioned [here](https://github.com/EventFahrplan/EventFahrplan/pull/434#pullrequestreview-842892565) it would help with the visibility if the background is white, because in that case the ScrollBar would be white on white.

**Comment by isiko** [comment]
I would do this, as I allready have part of a fix for this

**Comment by johnjohndoe** [comment]
Yes, this is definitely a place that needs improvement. Here is a rough idea of how it could work:

- [ ] Extracting a color resource for the `main` build flavor.
- [ ] Overwriting the color in the other build flavors if needed, e.g. `ccc36c3`.
- [ ] Wrapping the color resource into a style in `styles_congress.xml` if needed.
- [ ] Applying the style to the `ListView` or just to the `ScrollBar` if possible in the favorites and schedule changes screens.

The difficult thing here will be to find out how to address the scroll bar style of a `android.widget.ListView`.

**Comment by johnjohndoe** [comment]
@isiko Please remember to create a **separate** branch for each topic/pull request. Please do **not** commit on the `master` branch. More here [contribution guideline](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md).

**Comment by isiko** [comment]
I wrote a simple implementation of this earlier, which can be found [here](https://github.com/isiko/EventFahrplan/tree/customScrollBar). It doesn't seem to be possible to change the ScrollBar directly, the only possible way seems to be to specify a drawable which is then displayed instead of the transparent rectangle. This can then be used to define color, radius of the corners, etc.In my implementation I simply took the `colorAccent` as color, but this could also be controlled differently, e.g. by another color variable.


Here is a picture of the current state:
<img src="https://user-images.githubusercontent.com/44641688/149637158-45eda248-3b24-4cdb-9e07-735f443694de.png" width="300">

I would appreciate a short comment if this is OK or what could be improved.
(Radius and width are stored as variables in `dimens.xml` and can be changed freely).

**Comment by johnjohndoe** [comment]
I had a short glimpse over your implementation. It looks good so far. - Take your time. I will take a look tomorrow or at the beginning of the week.

It is well possible that `android.widget.ListView` does not allow to be styled. Did you have a look at the [source](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/ListView.java?q=android.widget.ListView)? There might be a way to address the property via an `?attr/` reference. (Pure guessing).

The favorites screen uses a [different theme](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/AndroidManifest.xml#L80).

**Comment by isiko** [comment]
> It is well possible that `android.widget.ListView` does not allow to be styled. Did you have a look at the [source](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/ListView.java?q=android.widget.ListView)? There might be a way to address the property via an `?attr/` reference. (Pure guessing).

I didn't know this page existed, but there isn't much information about adding your own ScrollBar unfortunately, the only helpful pages I found were stackoverflow posts like [this one](https://stackoverflow.com/questions/14171755/custom-scrollbar-android#14487645). I also searched the documentation, but the only thing I found there were the attributes I already used in the code. This seems to indicate that the preferred method for adding a custom ScrollBar is to add a `scrollbarThumb`.
 
> The favorites screen uses a [different theme](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/AndroidManifest.xml#L80).

Thanks for pointing that out, I didn't realize that 😄 I copied my changes into the `NoActionBar` theme so it now works in the `schedule_changes` and `settings` screen, but somehow the favorites page only seems to accept the changes when I paste them directly into the `fragment_favorites_list.xml` and `fragment_favorites_list_narrow.xml` files. I guess I will just have to take a closer look at this.

**Comment by isiko** [comment]
Ok, after not finding anything in the layout files, I started to examine the code and finally got lucky. It seems that in several lines of code the `Theme_AppCompat_Light` is used instead of the `Theme_Congress_NoActionBar` or `Theme_Congress`. The line that caused the problem with the Favorites screen was [this](https://github.com/EventFahrplan/EventFahrplan/blob/44898d5b21cd117efcf24d33d5b03efba10a949a/app/src/main/java/nerd/tuxmobil/fahrplan/congress/favorites/StarredListFragment.kt#L98) line, but a search for `Theme_AppCompat_Light` brought up two other results ([here](https://github.com/EventFahrplan/EventFahrplan/blob/44898d5b21cd117efcf24d33d5b03efba10a949a/app/src/main/java/nerd/tuxmobil/fahrplan/congress/base/SessionsAdapter.java#L44), and [here](https://github.com/EventFahrplan/EventFahrplan/blob/44898d5b21cd117efcf24d33d5b03efba10a949a/app/src/main/java/nerd/tuxmobil/fahrplan/congress/changes/ChangeListFragment.kt#L64)). Since I have been working on this project for less than a month, I would like to hear from you if this line is correct or if it was simply overlooked and should be changed, bevore commiting my fix.

((I would only fix the line that caused my problem, the others should probably be fixed in another issue by someone more familiar with the code))

**Comment by johnjohndoe** [comment]
The theme/styling was added in the early days of the project (2014), see cea61b4e2382b32d869601d09b312cb44342c85e (initial style adjustments to changes screen) and b29e454f90c82c2e105954457535e53287e51980 (using AppCompat) and 66057d00e47979b6dc40a92b5740bf3a0c3d41ae (adding favorites screen as a copy of the changes screen).

Feel free to challenge everything in this project. There might always be an old decision which is no longer valid. Especially styling and theming is hard to get right. Once we run the app (and its flavors) we will find out if changing this has no side effects.
