### ISSUE TITLE
[Feature] Allow rating of talks from within the app

### ISSUE THREAD

**Issue by AlbrechtStriffler** [EventFahrplan/EventFahrplan#45]
During the congress, we are encouraged to rate the talks. Right now, this seems to only be possible via the link provided on https://events.ccc.de/, but not natively from inside the app.
Unfortunately, rating via the web site is pretty clunky and not optimized for mobile. 
Would it be possible to add this feature?

**Comment by johnjohndoe** [comment]
Thank you for pointing this out. I might be able to add the feature soon after the congress.

**Comment by AlbrechtStriffler** [comment]
That was quick, thanks! Do you have a date for the 1.33.4 release yet? (Trying to decide wether to wait for the release or maybe do the rating on the events.ccc.de page.)

**Comment by johnjohndoe** [comment]
@AlbrechtStriffler I released the version yesterday night in the beta channel of Google Play. If you sign up as a beta tester there then you can update immediately. The link can be found at the bottom of the Google Play page of the app.
