### ISSUE TITLE
Detach repo

### ISSUE THREAD

**Issue by rugk** [EventFahrplan/EventFahrplan#46]
Can you please detach this repo from the not maintained fork?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by johnjohndoe** [comment]
@rugk Thank you for the suggestion. @tuxmobil started and grew the project over many years and stopped for his own reasons about two years ago. Therefore he should be credited for his work as you mentioned.
Actually, I linked to tuxmobil's repository on purpose by contacting the GitHub support. The repository was not linked at its creation time due to technical reasons.
I also credited @tuxmobil in the `README.md as` you can read in the **history** section.

For now I will leave it as is but I am open to hearing other opinions. I will leave the issue open for a while.

**Comment by rugk** [comment]
Well… I actually don't think it makes sense to link to a unmaintained repo. I mean totally credit the original author in many places, but this link goes to the repo, not the author. I've listed my arguments already.

Given no one else reacted since 34c3 though, I'll close it now. :smile:

**Comment by rugk** [comment]
One congress and one year later I stil have the same opinion. Uhm just detach.

And why am I assigned?

Also the reason why nobody reacts is probably because nobody cares, just because this is not bad bug or so… :smile:

**Comment by johnjohndoe** [comment]
@tuxmobil would you be okay with changing the connection between your and this repository? It would mean that this repository becomes the major upstream repository. 

# Before
> EventFahrplan/EventFahrplan forked from tuxmobil/CampFahrplan

# After
> tuxmobil/CampFahrplan forked from EventFahrplan/EventFahrplan

To accomplish this we both need to contact the GitHub support and ask them to change the connection. I did that before for another project.

**Comment by johnjohndoe** [comment]
The link between [this repository](https://github.com/EventFahrplan/EventFahrplan) and [tuxmobil/CampFahrplan](https://github.com/tuxmobil/CampFahrplan) has been reversed by the GitHub support today upon my request.

![tuxmobil/CampFahrplan](https://user-images.githubusercontent.com/144518/90028935-8d3f8700-dcba-11ea-9f5c-642043f254a2.png)

![EventFahrplan/EventFahrplan](https://user-images.githubusercontent.com/144518/90029011-a21c1a80-dcba-11ea-9b66-472455703ad8.png)
