### ISSUE TITLE
Include links to recordings

### ISSUE THREAD

**Issue by torantal** [EventFahrplan/EventFahrplan#48]
Is there information available to update infos on past talks with links to https://media.ccc.de / [chaosflix](https://github.com/NiciDieNase/chaosflix)?

If so, the app would remain a very valuable tool after the last conference to rewatch favourites or discover more.

**Comment by johnjohndoe** [comment]
Thank you for your feature request. I worked on this in the past and will look into it again. I also noticed the new [ChaosFlix](https://github.com/NiciDieNase/chaosflix) app and the [cccTV](https://github.com/stefanmedack/cccTV) app. An integration would be interesting indeed. I however did not manage to meet @NiciDieNase nor @stefanmedack during 34C3 to brainstorm about it.

**Comment by stefanmedack** [comment]
Sounds like a good idea to pool our knowledge and code. Maybe we could use the Berlin Meetup Slack to get a discussion starting?

**Comment by johnjohndoe** [comment]
I would like to keep the discussion as transparent as possible and therefore prefer staying here.

**Comment by johnjohndoe** [comment]
@saerdnaer @MaZderMind Would it be possible to include links to recordings in the _schedule.xml_ once they are published?

**Comment by johnjohndoe** [comment]
@stefanmedack @NiciDieNase Do your apps support an intent filter for the host `media.ccc.de`? If the schedule app opens such an URL your app could take over the request.

**Comment by stefanmedack** [comment]
The [cccTV App](https://github.com/stefanmedack/cccTV) does not yet have intent filter for media.ccc.de, because it does not make sense for a TV-only App. However, I will definitely add it to a future mobile App version.

**Comment by NiciDieNase** [comment]
I'm currently working on handling media.ccc.de urls in chaosflix (touch).

**Comment by johnjohndoe** [comment]
@torantal The feature to share individual sessions or all favorites has been implemented and released in version 1.42.0 of the [_36C3 Schedule_ app](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule). See #241 for more details and screenshots. Please close this issue if the feature satisfies your request or leave a comment below.

**Comment by johnjohndoe** [comment]
Closing it myself now.
