### ISSUE TITLE
Notification when starring a talk

### ISSUE THREAD

**Issue by Chase22** [EventFahrplan/EventFahrplan#484]
# Environment
- App version: 1.54.0-DEBUG
- Android version:
- Branch: master
- Device: android-emulator

# How to reproduce
1. Open a talk in the overview
2. Star the talk by using the star button

# Observed behavior
- The talk is added as a starred talk but no direct feedback is given to the user

# Expected behavior
- Some feedback (Snackbar, Toast etc) should be given to the user

**Comment by johnjohndoe** [comment]
Thank you for your report. 

There is actually a visual feedback. The star icon you tapped changes from `+` to `-`. Does that happen on your device?

**Comment by Chase22** [comment]
It does happen, but i think it's very easy to miss. Imo it's generally a good idea to give feedback via toast to the user when an action is performed

**Comment by johnjohndoe** [comment]
Not sure if I agree. I would argue that missing this is a weakness of the icon state. Maybe we should instead evaluate if different icon states help with the visual feedback of the interaction.

**Comment by isiko** [comment]
I would partly agree with Chase22 here, the Icon change is quite subtle, maybe instead of switching the Icon from displaying a `+` to showing a `-`, it could switch from just Displaying the Outlines to Displaying a fully filled out star? This could also be applied to the Bell Icon used for Alarms
