### ISSUE TITLE
Android 12+: Stretch overscroll effect breaks schedule screen interaction

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#488]
# Environment
- Android version: 12 (API 31) or newer
- Branch: `master`

# How to reproduce
1. Visit the schedule screen at the first column
2. Try to scroll before the first column (the column items stretch a little and the spacing on the right is lost)
3. Try to tap a session in the first column to open it

# Observed behavior
- The session won't open anymore.

  https://user-images.githubusercontent.com/144518/178827021-d241026c-cdb8-4488-8b16-1aa9a5dcb584.mp4

# Expected behavior
- The session details are shown.

# Workaround
- Rotate the device to re-render the schedule screen.

# Related
- [Android 12: Behavior changes / Stretch overscroll effect](https://developer.android.com/about/versions/12/behavior-changes-all#overscroll)

**Comment by isiko** [comment]
I searched a bit and found [this](https://stackoverflow.com/questions/71248264/how-to-disable-programmatically-android-12-elastic-scroll-animation) StackOverflow post about how to get rid of that animation. I implemented it and it works for me.

It should be noted that there is [this](https://support.google.com/pixelphone/thread/132936922?hl=en&msgid=157271760) post on a Google forum that warns of this approach, but I could not find any Bugs so the error probably only occurs when applied via the system settings.

I committed my fix to [a branch on my fork](https://github.com/isiko/EventFahrplan/tree/removeHorizontalOverscroll), so if you want you can also look if you find any resulting Errors.

**Comment by isiko** [comment]
Also, I'm just realizing that this isn't just the Android 12+ Overscroll effect, but all overscroll effects, so if you like this fix I would add a check to only disable overscroll animations in Android 12+ before opening a pull-request

**Comment by johnjohndoe** [comment]
@cketti suggested to look into the touch handler. Maybe the implementation could be improved.

**Comment by johnjohndoe** [comment]
@isiko Sadly the issue has not been resolved or returned. It is very annoying when sessions can no longer be opened by tapping them. I will re-open this issue now.
