### ISSUE TITLE
Replace PNG with SVG icons

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#510]
# Context
- In earlier versions of Android only PNG images could be used which required to provide the same images in different resolutions.
- At some point support for SVG images was added and backported to older Android versions.

# Current state
- Menu and alarm icons are still implemented as PNG files. 
- See `drawable`, `drawable-*dpi`, `mipmap-*dpi` folders.

# Target state
- Menu and alarm icons are implemented as SVG files.
- If needed new SVG icons have to be found or designed. New icons should be proposed to be discussed up-front.
- Users should not notice a difference (if the same icons are used).
- SVGs are stored in the [assets](https://github.com/EventFahrplan/EventFahrplan/tree/master/assets) folder 
- SVG files are prepared so they can be tinted in the future if needed.

# Hints
- Programs like [Inkscape](https://inkscape.org) and [svgo](https://github.com/svg/svgo) are useful.
- [Add multi-density vector graphics](https://developer.android.com/studio/write/vector-asset-studio)
- [Vector drawables overview](https://developer.android.com/develop/ui/views/graphics/vector-drawable-resources)
- former SVGs are partially stored in the [assets](https://github.com/EventFahrplan/EventFahrplan/tree/master/assets) folder

**Comment by sachin2709** [comment]
I want to work on this task, Please assign it to me sir @johnjohndoe

**Comment by johnjohndoe** [comment]
Nice. Let me know when you have questions. I will try to answer as soon as possible.

Please prepare the SVG file so they can be tinted in the future if needed.

**Comment by johnjohndoe** [comment]
@sachin2709 Did you change your mind? Do you no longer want to work on this task?

**Comment by sachin2709** [comment]
Yes Sir, I don't want to do @johnjohndoe

**Comment by isiko** [comment]
I'd like to work on this Issue

**Comment by johnjohndoe** [comment]
@isiko Give a shot. :+1: Please do the icon change in a separate commit please so it can easily reverted if needed.

**Comment by isiko** [comment]
I've now migrated most of the Icons, which can be seen [here](https://github.com/isiko/EventFahrplan/tree/switchToVectorImages). I added 3 more Icon changes:
* There was a custom Video Camer Icon which I changed to a standard Material Icon (Also I removed it in some locations where it wasn't used anymore
* For the Calendar Icon I found a Material Icon which is extremely Similar but not 100%, so I put that in a separate commit
* For the Feedback Icon I used one from the Material Icon set, partly because I think it fit's better and partly because I wanted less work

I'm just missing the 3 custom List Icons (`ic_action_bell_list_white`, `ic_action_healing_list_white`, `ic_action_star_list_white`) Now my Question would be if you still have the files used to create those Icons? (Like project files or many even the original vector images)

**Comment by johnjohndoe** [comment]
Former SVGs are partially stored in the [assets](https://github.com/EventFahrplan/EventFahrplan/tree/master/assets) folder.

Please prepare the SVG file so they can be tinted in the future if needed.

**Comment by isiko** [comment]
Is there a meaningfull difference between [this](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/rc3/res/drawable/ic_novideo.png) and [this](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/res/drawable/ic_without_video_recording_took_place.png) Icon? If not, I would like to just merge them.

**Comment by johnjohndoe** [comment]
There is a difference. Have a look where and how they are used. If I am not mistaken the less saturated icon is used for sessions in the favorites screen which **had happened** (matching the text color) while the black icon is used for **future** session (matching the text color). You might be able to merge the icons by tinting them depending on the use case. Not sure if tinting works with a multi-color icon.

**Comment by johnjohndoe** [comment]
I found the "feedback_thumb_up" SVG file: ![feedback_thumb_up](https://user-images.githubusercontent.com/144518/194165493-03ae0c48-49e5-4903-8a4d-e404af4061b9.svg)

**Comment by johnjohndoe** [comment]
> I'm just missing the 3 custom List Icons (`ic_action_bell_list_white`, `ic_action_healing_list_white`, `ic_action_star_list_white`) Now my Question would be if you still have the files used to create those Icons? (Like project files or many even the original vector images)

I created these icons (I guess you saw this [here](https://github.com/EventFahrplan/EventFahrplan/commit/5df41892a7f6fe5069b97148305415b3c5d8bc1f)). I remember I used the Material icons set (SVG) to compose the icons by combining existing icons with [Inkscape](https://inkscape.org). I did not find straight away - I can have a longer look if you want. Otherwise I believe they can be recreated.

**Comment by isiko** [comment]
> Oh. I just saw that you (found? and) added the SVGs to the assets folder already.

I Just Recreated them :+1:
