### ISSUE TITLE
Download selected talks from media.ccc.de

### ISSUE THREAD

**Issue by Siltaar** [EventFahrplan/EventFahrplan#52]
Once you've chose the talks you want to attempt, it looks straight forward to be asked which talks you really attended.

Then, a common usage I noticed during the 34c3 is to spend time each of the last days of the event to download the talks you wanted to be in, but missed… So what about downloading All selected talks or All missed talks from the EventFahrplan app directly on your phone ? (to watch the talks later, for instance in the return train).

**Comment by johnjohndoe** [comment]
@Siltaar Thank you for your feature request. As you can read in #48 I am planning to integrate with [ChaosFlix](https://github.com/NiciDieNase/chaosflix) and [cccTV](https://github.com/stefanmedack/cccTV). We still have to figure out the details but we will certainly pick up your idea. Stay tuned.

/cc @nicidienase + @stefanmedack

**Comment by pseyfert** [comment]
for reference, downloading favorites is also suggested in https://github.com/mfherbst/down-frab-videos/issues/15

**Comment by johnjohndoe** [comment]
@Siltaar The feature to share individual sessions or all favorites with the [_Chaosflix_ app](https://play.google.com/store/apps/details?id=de.nicidienase.chaosflix) has been implemented and released in version 1.42.0 of the [_36C3 Schedule_ app](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule). See #241 for more details and screenshots. 

As far as I know the [cccTV](https://github.com/stefanmedack/cccTV) app development is discontinued. Therefore, I will not work on an integration for it.

I am closing this issue now. You are still welcome to comment on this issue or open a new issue for a new topic. Thank you for posting your feature request.
