### ISSUE TITLE
Migrate database(s) to Room

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#53]
# Current state
- Four separate databases are used to store _lectures_, _meta_, _alarms_, _highlights_ (aka. _favorites_).
- Databases are accessed via custom classes extending `SQLiteOpenHelper`.
- SQL code fragments is spread throughout the applications.
- Inter-table logic is implemented programmatically not on the database level due to separate databases.
- No unit tests.

# Target state
- [x] Encapsulate database within its own Android Studio module.
- [x] Provide abstraction layer (repository) to access the database module.
- [ ] One database is used.
- [ ] Database is accessed via [Room](https://developer.android.com/topic/libraries/architecture/room.html).
- [ ] Foreign keys are used to persist inter-table logic.
- [ ] Repository pattern is used to layer access to the data source (database, ...).
- [ ] Data source is unit tested.

**Comment by johnjohndoe** [comment]
Status update: Not sure if the migration to Room still makes sense. Let's discuss.

**Comment by johnjohndoe** [comment]
For now I decided not to work on the database layer due to priorities and limited resources.

**Comment by zoff99** [comment]
room means abandon older android versions

**Comment by johnjohndoe** [comment]
@zoff99 Are you referring to that Room raises the `minSdkVersion`?

**Comment by zoff99** [comment]
yes

**Comment by johnjohndoe** [comment]
@zoff99 Thank you for the hint. 
However, at some point this will happen because other libraries such as [OkHttp v.3.13.0](https://square.github.io/okhttp/changelog_3x/#version-3130) have raised the `minSdkVersion`.
I will migrate to `androidx` since the legacy support libraries will not be updated any longer.
