### ISSUE TITLE
Add page indicator so horizontal scrolling becomes obvious

### ISSUE THREAD

**Issue by thibaultmol** [EventFahrplan/EventFahrplan#532]
Currently the app that was published to FDROID
https://f-droid.org/packages/info.metadude.android.fosdem.schedule/
doesn't show the lightning talks, even though that's actually one of the more convoluted things to keep track of when it comes to the FOSDEM schedule
https://fosdem.org/2023/schedule/track/lightning_talks/

**Comment by johnjohndoe** [comment]
@thibaultmol Thank you reaching out. 

Please check again. I can see the lightning talks being included in the [XML file](https://fosdem.org/2023/schedule/xml) which is consumed by the app. In the app swipe horizontally until you reach room `H.2215 (Ferrer)`.

**Comment by thibaultmol** [comment]
OH. sorry, wasn't clear to me that horizontally swiping was a thing I could do in the app.
I guess it's not easily user discoverable?
Maybe adding an indicator for that might help, like this https://raw.githubusercontent.com/vivchar/ViewPagerIndicator/master/example.gif

**Comment by johnjohndoe** [comment]
Agreed, a page indicator might be helpful. Do you want to come up with a UI sketch? The challenge is to not hide session elements under the indicator. Please mind that the session elements can be very small.

**Comment by thibaultmol** [comment]
Wouldn't this be the solution?
![image](https://user-images.githubusercontent.com/1010226/216573263-9080c743-0ae1-4003-93f1-7f724c80e31e.png)

**Comment by johnjohndoe** [comment]
I could imagine something like this being shown as an overlay at the bottom of the screen which is only shown as long as the user scrolls. Once the user stops the indicator should fade out to avoid overlaying the text of session items. Here is a few cases which need to be taken in consideration:

1. Do not overlay session items permanently
2. Do not conflict with Toast messages being shown
3. Do not conflict with Snack messages being shown
4. Tablet / landscape: do not conflict with open side panel
