### ISSUE TITLE
Add 'calendar' view to favorites 

### ISSUE THREAD

**Issue by thibaultmol** [EventFahrplan/EventFahrplan#533]
# Acknowledgments
Please check the following boxes with an `x` if they apply:
* [x] I have read the latest version of the [contribution guide](
  https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before creating this pull request.
* [x] I have checked a few other issues labeled `Feature request` to see how they are written.
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that _EventFahrplan_ is mostly developed by one person in their unpaid spare time.
* [x] I can help myself to get this feature implemented or know someone who wants to do it.

# Preliminaries

I prefer seeing the events in a calender view, where you can easily see white space between each events or if events are overlapping

# Current state

Favorites only show a list atm, sorted chronologically. but still just a list

**Comment by johnjohndoe** [comment]
Thank you for the feature request.

Did you see that every session you favor is highlighted by adding a border around the box? That is how favorites are visualized.

Depending on the device and orientation you will see sessions incl. favorites in the grid view. On a phone in landscape mode you see four columns, on a 10" tablet you see six columns.

Does this satisfy your feature request?

**Comment by thibaultmol** [comment]
Not really actually. I did notice the highlithing. But because fosdem has so many tracks, using that isn't really useful. I can only attend one thing at a time, so a simple calendar view like on the main screen, but with only my favourites. Might be better.

**Comment by johnjohndoe** [comment]
If I understand you correctly what you are looking for is a filter functionality as discussed in #3.

Please mind while hiding sessions which are not favored all your favorites would still show up as now: maximum four rooms on a phone in landscape, ...

Can you maybe visualize your idea of you think of something else?

**Comment by thibaultmol** [comment]
No actually, what I meant was just the same vertical timeline view like in the first app view. where you see all the events from top to bottom. The regular view.

But if I click on the Favorites button. Opens up a new view that has the same ui. but only shows the favorited events.

I guess a filter option could make that work. But it should be something that you can easily switch to

**Comment by johnjohndoe** [comment]
OK. I think the discussion can therefore continue in #3. Thank you for the clarification. I am closing this issue as a duplicate.
