### ISSUE TITLE
Feature request: room status support

### ISSUE THREAD

**Issue by bzz** [EventFahrplan/EventFahrplan#55]
AFAIK that is the first year when room status is available thought API at https://sojourner.loomchild.net/#/tracks

It would be grateful to incorporate it into the app somehow, so people could make more confident decisions attending the tracks.

**Comment by johnjohndoe** [comment]
@bzz Thank you for your feature request. This feature was announced by Mark Van den Borre at 30.12.2017 via email to a number of application maintainers targeting the [FOSDEM conference](https://fosdem.org). As a result of the conversation some apps implemented the feature while others suggested that the feature needs a standardization and buy-in from all conference management systems (Pentabarf, Frab, ...).

With regards to this codebase the room status would be a FOSDEM-only feature. I decided not to implement it for 2018. One major reason was that I did not have the time to work on the implementation before FOSDEM 2018 took place.

I will close the issue for now - however feel free to comment here. Thank you for pointing out the feature!
