### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by Xyz00777** [EventFahrplan/EventFahrplan#558]
# Environment
- App version:1.61.0-CCCamp-Edition
- Android version:11
- Branch:?
- Device:Oneplus

# How to reproduce
1. Open the app
2. click on one stream
3. look at the link/click on the link

# Observed behavior
- every link is broken because they have two "/" at one point at the link  

# Expected behavior
- the links shouldnt be broken :D

**Comment by johnjohndoe** [comment]
Thank you for reporting this. 👍 I forwarded it to be fixed by the VOC who takes care of the schedule data.

**Comment by johnjohndoe** [comment]
This has been fixed by the backend during the event. Hence, closing here. Thanks.
