### ISSUE TITLE
Parsing error for schedule

### ISSUE THREAD

**Issue by Woazboat** [EventFahrplan/EventFahrplan#559]
# Environment
- App version: 1.61.0-CCCamp-Edition
- Android version:
- Branch:
- Device:

# How to reproduce
1. Open the app
2. Popup with error message appears at bottom

# Observed behavior
Error popup with message "Parsing error for schedule version 2023-08-13 21:26"

# Expected behavior
Schedule for CCCamp23 should be loaded

Don't know if this is an issue in the app or with the schedule resource on the server?

**Comment by johnjohndoe** [comment]
Thanks for reporting. I can reproduce the issue by fresh installing the app.

It seems to be an issue with the schedule served by the VOC team. I will forward it to them.

**Comment by saerdnaer** [comment]
Technically this year is the merged schedule is provided by the HUB team :-) – but there is some personal overlap...  

When I validate https://events.ccc.de/camp/2023/hub/api/c/camp23/schedule.xml with https://c3voc.de/schedulexml/ I only get an irrelevant error about a to short slug
<img width="893" alt="image" src="https://github.com/EventFahrplan/EventFahrplan/assets/40266/ae946fca-fb7f-412e-aa0a-dd7baa887134">

How can I get more details on the parsing errors

**Comment by elcorto** [comment]
I don't see a way to export debug info in the app, but since @johnjohndoe was able to reproduce this via a fresh install, I don't think it is due to an oldish xml parser library on my (quite dated) device.

Cloud it be a permission issue? My system app settings claim that the app doesn't require any, is that correct?

**Comment by johnjohndoe** [comment]
@saerdnaer found out that the cause of the error is a session with a duration of two days. The schedule should be adapted soon. - Thanks for the work!

**Comment by elcorto** [comment]
Thanks a lot, that partiality solved it. The schedule updated (I guess once) and I can see the program.

However when I refresh, I still see the parsing error, so I assume I won't get any updates.

**Comment by saerdnaer** [comment]
We are aware of the underlying problem and will now format durations > 24h as `day:hh:mm` instead of `hh:mm`

**Comment by johnjohndoe** [comment]
@elcorto You might need to reset resp. reinstall the app. I can't tell from where I am. Make sure to export your favorites before.

**Comment by code4candy** [comment]
Same error on Samsung Galaxy S21 with Android 13: 
"Parsing error for schedule version 2023-08-15 ..."
The schedule does not show at all. Reinstalling the app does not change anything.

**Comment by geobra** [comment]
Same here. Deleting all cache and config data, then deleting and reinstalling the App does not solve the issue on my side. Is the json schedule fixes meanwhile?

**Comment by cketti** [comment]
The [schedule](https://events.ccc.de/camp/2023/hub/api/c/camp23/schedule.xml) version "2023-08-15 12:35" contains a bunch of duration values like `02:120` that the app can't parse.

I'm guessing you're starting with a duration value in minutes and the code to compute the duration XML value looks something like this:

```
hours = minutes / 60
mins = minutes

value = format("%02d:%02d", hours, mins)
```

If that's the case, fix it by using `mins = minutes % 60` instead.

**Comment by cketti** [comment]
> We are aware of the underlying problem and will now format durations > 24h as `day:hh:mm` instead of `hh:mm`

Chances are this will be parsed as `h:mm:ss` by existing clients. If you're changing the format (and thus breaking clients) anyway, why not switch to using minutes?

**Comment by elcorto** [comment]
Deleted cache and app data, reinstalled the app..did not fix the issue. Still seeing the parsing error.

**Comment by johnjohndoe** [comment]
@saerdnaer Are you able to rewrite the schedule (split long sessions) without changing the Android app to fix the parsing error?

**Comment by johnjohndoe** [comment]
Acknowledgement: I will not be able to publish an app update. I am several thousands of kilometers away from my computer until after the Camp.

**Comment by elcorto** [comment]
Schedule parsing and updates work as of today, 2023-08-15, 4pm CEST or thereabouts. Thanks!
