### ISSUE TITLE
Design of an EventFahrplan logo

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#567]
Status: :green_circle: Ready to work on

# Preliminaries
- Currently, the project uses a simple typographic EF logo as its visual brand recognition. 

![ef-logo](https://github.com/EventFahrplan/EventFahrplan/assets/144518/cc0d56d9-e67b-4db8-9af4-dfc5b96524e4)

# Requirements
- The logo must visually represent the unique selling point of the app, e.g. the session grid.
- It must be unique to clearly separate the project from other event apps.
- Must be a plain SVG file, gradients turn out to cause problems in Android Studio’s conversion to the [vector drawable](https://developer.android.com/develop/ui/views/graphics/vector-drawable-resources) format. The project file format can be application specific, e.g. Adobe Illustrator, Inkscape.
- Must be licensed as CC BY-SA 4.0. The creator of the logo will be attributed in the repository of the project.

# Usage
The logo must be usable as the brand for the project in different scenarios and sizes:
- browser favicon (very small): https://eventfahrplan.eu
- logo for the GitHub organization: https://github.com/EventFahrplan
- Android app icon (round base shape to not cut off parts)
- website banner
- social media icon (Twitter, Mastodon, …)
- stickers
- t-shirt print (large)
- external websites referencing the project

# Hints
- A round or square base shape probably makes most sense.
- The original project file and resulting plain SVG must be stored in the [EventFahrplan-media](https://github.com/EventFahrplan/EventFahrplan-media) repository.

**Comment by taseret** [comment]
I like to work on this

**Comment by johnjohndoe** [comment]
:heavy_check_mark: This task has been successfully finished. See https://github.com/EventFahrplan/EventFahrplan-media.
