### ISSUE TITLE
Design static graphics for empty screens

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#568]
Status: :green_circle: Ready to work on

# Preliminaries
- Screens such as favorites, alarms and schedule updates are empty by default.

![favorites-empty](https://github.com/EventFahrplan/EventFahrplan/assets/144518/9043e5c6-324e-4827-a9b0-da6666c7659d) ![alarms-empty](https://github.com/EventFahrplan/EventFahrplan/assets/144518/d7ee8045-e6c0-4c81-a92a-46cf802e90b7) ![schedule-changes-empty](https://github.com/EventFahrplan/EventFahrplan/assets/144518/f3a447eb-a36b-409f-b09f-cc5faef4af2c) ![leer](https://github.com/EventFahrplan/EventFahrplan/assets/144518/555ea9ee-732a-4b19-87dd-3ebcc240ece8)

- A textual instruction is shown to tell users what to expect and how to use the individual feature.

# Task
- Create a static graphic for each screen which illustrates the given information, eases to understand the empty state and makes the screen itself more pleasant or even funny.
- Take other apps such as Gmail, Google Contacts (search) as a source of inspiration.
- List references below or link them if available online.

# Screens
- favorites
- alarms
- schedule updates
- speakers (does not exist yet)
- search results (does not exist yet, see #3)
- initial installation, no schedule available to load yet
- no network connection

# Requirements
- The graphics must be designed to work both on bright and on dark backgrounds and with different colors. Take a look at [existing EventFahrplan apps](https://play.google.com/store/apps/dev?id=6885964602402432210) to see color variants.
- The graphics must use one color to allow [tinting](https://developer.android.com/jetpack/compose/graphics/images/customize#tint-image).
- Use plain SVG. The project file format can be application specific, e.g. Adobe Illustrator, Inkscape.
- The graphics must be themed neutral enough to work for all kinds of events and not themed for a specific event context, e.g. a tech conference, acrobatic gathering.
- Must be licensed as CC BY-SA 4.0. The creator of the graphics will be attributed in the repository of the project.

# Hints
- The project files and the plain SVGs must be stored in the [`assets` folder](https://github.com/EventFahrplan/EventFahrplan/tree/master/assets) of this repository.

**Comment by taseret** [comment]
I like to work on this

**Comment by taseret** [comment]
I have collected some inspiration for the illustrations here:
![empty_screens_inspiration](https://github.com/EventFahrplan/EventFahrplan/assets/141333487/8e3204c6-7f9b-4bca-a98f-4299db507990)

**Comment by johnjohndoe** [comment]
Here are a few that I collected:

![twitter_01](https://github.com/EventFahrplan/EventFahrplan/assets/144518/94f919ed-c5e9-4767-b900-ffac5a0a6607) ![twitter_02](https://github.com/EventFahrplan/EventFahrplan/assets/144518/ad406e7a-b749-42f7-ad86-963eb78d2586)

![tusky_01](https://github.com/EventFahrplan/EventFahrplan/assets/144518/bc467266-4cb6-4173-afe1-e54f4a63e079) ![tusky_02](https://github.com/EventFahrplan/EventFahrplan/assets/144518/8b85075e-f6b1-4194-8507-bf59bdcf60ae)

**Comment by johnjohndoe** [comment]
@taseret I added "no network connection" as an optional screen to the list.

**Comment by taseret** [comment]
![Bildschirmfoto 2024-03-28 um 21 07 03](https://github.com/EventFahrplan/EventFahrplan/assets/141333487/217159d5-5041-4d8d-858b-9acb03de7539)

**Comment by taseret** [comment]
@johnjohndoe added the new changes icon to the repository

**Comment by johnjohndoe** [comment]
# Google payments center / Subscriptions & services

![image](https://github.com/user-attachments/assets/cc4aaa85-1432-484b-955c-134afa6a9c82)
