### ISSUE TITLE
iOS Version 16.7.4 can’t install app from App Store 

### ISSUE THREAD

**Issue by windrad6** [EventFahrplan/EventFahrplan#591]
# Environment
- App version:
- Android version: not Android iOS 16.7.4
- Branch:
- Device: iPhone 8

# How to reproduce
1. Try to install from App Store
2. Search for 37C3
3. Try to install

# Observed behavior
- See screenshot. When installing the RC3 version is installed and the timetable is outdated.
<img width="375" alt="image" src="https://github.com/EventFahrplan/EventFahrplan/assets/37443948/04f0c8bb-0cc1-4311-87bd-10583c511980">

# Expected behavior
- Installing current version

**Comment by isiko** [comment]
This is the Android App, the iOS App has a different Repository

**Comment by johnjohndoe** [comment]
Thank you for the report. Please reach out to the maintainer of the iOS project. I close the issue here.
