### ISSUE TITLE
Timeline no longer shown if time is past 00:00 in the current day

### ISSUE THREAD

**Issue by powelllens** [EventFahrplan/EventFahrplan#593]
# How to reproduce
- past 00:00 o'clock
- select current day

# Observed behavior
- What happened?
Blue indicator no longer shown in current day
Blue indicator is only visible on the next day (but with the wrong schedules)

- Add screenshot(s).
![Screenshot_20231228-013835.png](https://github.com/EventFahrplan/EventFahrplan/assets/6517959/4ffda41d-31b9-4162-891b-7d727b5f8fd9)

# Expected behavior
- What should happen?
Blue indicator should only be visible in day 1 even if it's past 0 o'clock to not mess up the schedule highlight

**Comment by johnjohndoe** [comment]
Thank you for reporting the issue. There is a similar issue here: https://github.com/EventFahrplan/EventFahrplan/issues/33. I like to invite you to follow-up there. I am closing this as a duplicate.
