### ISSUE TITLE
ssl fahrplan.events.ccc.de not verified: certificate

### ISSUE THREAD

**Issue by iamhermes** [EventFahrplan/EventFahrplan#594]
# Environment
- App version: 1.62.0
- Android version: 14
- Branch: UQ1A.231205.015
- Device: Google Pixel 7

# How to reproduce
1. Install app
2. Open and refresh

# Observed behavior
- What happened?
- no timeline loaded
- Zertifikat konnte nicht übernommen werden.

Aufbau einer gesicherten Verbindung nicht möglich.

(Hostname fahrplan.events.ccc.de not verified: certificate: sha256/5PU4CY872VcwGzxpZKS gpE0dg8MvTixGWEaZ8JwOKE=

DN: CN=events.ccc.de

subjectAltNames: [events.ccc.de, map.events.ccc.de])

![Screenshot_20231228-092411](https://github.com/EventFahrplan/EventFahrplan/assets/4535068/03981cdb-55cf-4c44-8496-bb47198d6004)

# Expected behavior
- What should happen?

# Related
- Link to related issues here if applicable.

**Comment by iamhermes** [comment]
Missing Subdomain in ssl certificate:
![Screenshot_20231228-094147](https://github.com/EventFahrplan/EventFahrplan/assets/4535068/e0d43087-4cc7-4a3a-bb98-63178d200149)

**Comment by johnjohndoe** [comment]
Thank you. The problem has been identified in the backend and will be fixed soon. Please try again later - the app will be fine.

**Comment by johnjohndoe** [comment]
The issue has been resolved by the backend team. Enjoy 37C3.
