### ISSUE TITLE
Share to JSON seems to be buggy? Sharing wrong information.

### ISSUE THREAD

**Issue by IsoLinearCHiP** [EventFahrplan/EventFahrplan#596]
Hi.

I was fiddling around with sharing to HTTP Requests and stumbled upon various fields in the json not ligning up in name and content.

Looking at: 

https://github.com/EventFahrplan/EventFahrplan/blob/9abc55d497833b60e6e1aed06ffd0ff8b4408a4e/app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt#L35-L41

I am suspecting a copy & paste error snuck in. Hopefully I'm on the right track and it's an easy fix.

Cheers.

**Comment by johnjohndoe** [comment]
@IsoLinearCHiP Thanks for spotting this error. Seems like it has been introduced here: https://github.com/EventFahrplan/EventFahrplan/commit/c90b6#diff-23cb4e83e7cd967569dcf7f8e7beeb24a3dd4d6315b0ffb0087ae6e11ff76cc7
Do you like to prepare a fix and a unit test for `SessionExport` so that the error does not happen again?

**Comment by IsoLinearCHiP** [comment]
@johnjohndoe Tryed to fix it as per your request. Struggled allot with the whole build environment, etc.

It delivers the output I expected, but I have no way of testing it with Chaosflix, as that app won't install on my tablet. I was just trying to hook it up with HTTP Request Shortcuts to see if I could chain it further to Orgzly.

Ill send you a pull request, hopefully its what you need.

**Comment by johnjohndoe** [comment]
> Struggled allot with the whole build environment, etc.

Please let me know in a separate issue or via [discussions](https://github.com/EventFahrplan/EventFahrplan/discussions) about the details. We might be able to ease the project setup or documentation. 

> I have no way of testing it with Chaosflix

I can try it myself later these days.

**Comment by IsoLinearCHiP** [comment]
> Please let me know in a separate issue or via [discussions](https://github.com/EventFahrplan/EventFahrplan/discussions) about the details. We might be able to ease the project setup or documentation.

Probably nothing you can do about it, I'm not an android dev, never used kotlin and haven't used android studio before. I'm used to firing up my editor of choise and then just running the interpreter over the main file. It just felt like overwhelming overhead to go through to edit 8 lines of code. Sorry for venting my frustration there, it is in no way a critisism towards your project, I was just way outside my comfort zone and it literally took hours getting all stuff installed and running. :-)

Thanks for your work🍺

**Comment by johnjohndoe** [comment]
Thank you for going through the hurdles! Maybe it becomes an investment for further contributions ^^ That would be great.
