### ISSUE TITLE
Broken time column rendering with event time of 00:00:00

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#61]
# Environment
- App/version: GPN, v.1.33.5
- Branch: [gpn-2018](https://github.com/johnjohndoe/CampFahrplan/tree/gpn-2018)
- Device: Nexus 9, Android 7.1.1

# How to reproduce
- Start the GPN app
- Navigate to day 3 from the top menu

# Observed behavior
- The dark time column view on the left side only shows the time entry of the first event as shown in the screenshot:
![gpn-1 33 4-screenshot](https://user-images.githubusercontent.com/144518/39972145-0160ac3e-5709-11e8-964b-ec19f9d8022e.png)

# Expected behavior
- The dark time column view on the left side shows the time entries in a regular series 15 minutes segments. Compare with day 1.

# Intermediate research
- The rendering bug seems to be caused by the event time of `00:00:00`.
- A snapshot of the schedule XML of GPN can be found [here](https://gist.github.com/johnjohndoe/9ca013c147def7354551f21f1b5010de) to reproduce the error.
- An insufficient bug fix has been applied [here](https://github.com/johnjohndoe/CampFahrplan/commit/96aa63a4450364adc0867fa14474b814b405b293) which fixed the issue for day 2 but not for day 3. Since this rendering issue can occur an any given time again a patch must be applied on the `master` branch.

**Comment by poschi3** [comment]
Tested snapshot of Fahrplan with current master. Problem was resolved by #98.

**Comment by johnjohndoe** [comment]
@poschi3 did you successfully test with the old GPN schedule file which I linked in the issue?

**Comment by poschi3** [comment]
@johnjohndoe Yes and I checked it now again. There is a correct time column for day 2 to 4. But now I noticed that there is no time column on day 1...

**Comment by johnjohndoe** [comment]
@poschi3 If this is specific to this issue (and GPN) then we should reopen the issue to be resolved at some point.

**Comment by johnjohndoe** [comment]
I have not see this bug for a long time. Closing here.
