### ISSUE TITLE
Session alarm notification not triggered on time

### ISSUE THREAD

**Issue by cbeyls** [EventFahrplan/EventFahrplan#612]
# Environment
- App version: 1.63.0-FOSDEM-Edition
- Android version: 13
- Device: Google Pixel 4a

# How to reproduce
1. Press the action bar button to program a notification for a session
2. Lock the device screen
3. Wait for the session time

# Observed behavior
- The notification is not triggered on time. It is delayed by up to 30 minutes, which is too late to catch up with the session.

# Expected behavior
- The alarm should be triggered at the exact time, even if the app is not in the foreground or the device is in sleep mode.

# Cause of the issue
The notification is scheduled by calling [`AlarmManager.set()`](https://developer.android.com/reference/android/app/AlarmManager#set(int,%20long,%20android.app.PendingIntent)). Since API 19, this method is only suitable to run deferrable background work (batched with other apps work), not for alarm clock-style alarms shown to the user.

# Solution
The notification must be scheduled using [`AlarmManagerCompat.setExactAndAllowWhileIdle()`](https://developer.android.com/reference/androidx/core/app/AlarmManagerCompat#setExactAndAllowWhileIdle(android.app.AlarmManager,int,long,android.app.PendingIntent)), and only after requesting the [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM) permission on API 31 (Android 12) and later.
On API >=31, [`AlarmManager.canScheduleExactAlarms()`](https://developer.android.com/reference/android/app/AlarmManager#canScheduleExactAlarms()) should be called to determine if the permission needs to be requested, and the alarm may only be scheduled after it has been granted.
On lower API levels, the permission doesn't exist and the alarm can be scheduled directly.

For reference, you can check [the commit](https://github.com/cbeyls/fosdem-companion-android/commit/53d9d5e60aca8468d84488a217fddb6174ca7121) where I added the permission handling to my app.

**Comment by johnjohndoe** [comment]
Thank you for reporting this issue and the effort of providing both the detailed analysis and the implementation reference!

It is indeed something that should be address as soon as possible (speaking of alarms ... *smirk*). I have seen the announcements before. I haven't come around to look into the topic for a while, though.

# Power-save exemption

> Apps targeting [Build.VERSION_CODES#S](https://developer.android.com/reference/android/os/Build.VERSION_CODES#S) or higher can schedule exact alarms only if they have the [Manifest.permission#SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM) permission or they are on the device's power-save exemption list. These apps can also start [Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_SCHEDULE_EXACT_ALARM) to request this permission from the user.

Source: https://developer.android.com/reference/android/app/AlarmManager#canScheduleExactAlarms()

Do you think requesting to be on the "device's power-save exemption list" is also required to have alarms being fired on time? Also [`PowerManager#isIgnoringBatteryOptimizations`](https://developer.android.com/reference/android/os/PowerManager#isIgnoringBatteryOptimizations(java.lang.String)) is mentioned on the page.

# Docs

Here is a few more links to the docs for later reference:

- [Android 12 / behavior changes: Exact alarm permission](https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission)
- [Android 14 / behavior changes: Schedule exact alarms are denied by default](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms)

**Comment by cbeyls** [comment]
It's not needed to add the app to the power-save exemption list, and it's probably a bad practice to encourage the user to do so for this kind of app.
However I noticed that on my device, even when granting the permission and using `setExactAndAllowWhileIdle()`, the alarm may still be delayed by a minute or two when the device is in sleep mode, but it's good enough.

Regarding the fact that you're also using AlarmManager to update the schedule data in the background: the recommended API to do this nowadays is Jetpack WorkManager. It allows to set constraints for the job (for example a network connection is required), a retry policy, and more.

**Comment by johnjohndoe** [comment]
Looking into the topic I noticed a few questions / shortcomings:

1. Why can I not invoke `permissionRequestLauncher.launch(SCHEDULE_EXACT_ALARM)` like for `POST_NOTIFICATIONS`? And why is there no warning that it is wrong if I do anyway?
2. Once I granted the system permission screen with `ACTION_REQUEST_SCHEDULE_EXACT_ALARM` and resume my app the `resultCode` is `RESULT_CANCELED` and tell nothing about whether the permission was granted or not. Isn't that very inconvinient?
3. When I launch the system permission screen from an app running with a different language (e.g. German) than the system language (e.g. English) then the system permission screen is shown in the system language (e.g. English). That seems to be not very helpful for users.

@cbeyls Did you notice these too? Any other?

**Comment by cbeyls** [comment]
Hi there, here are some quick answers:

1. In reality, `SCHEDULE_EXACT_ALARM` is a normal permission and not a runtime permission, so adding it to the manifest is enough to obtain it. However, obtaining the permission only does half of the job, as it only enables the "Alarms and Reminders" option panel in the system app settings. The second part of the job is to ask the user to go check the box in that panel, and as a shortcut you can launch the `ACTION_REQUEST_SCHEDULE_EXACT_ALARM` intent.
2. I didn't notice that issue, I receive `RESULT_OK` if the box is checked when returning to the app. Make sure you pass "package:${BuildConfig.APPLICATION_ID}" as uri data in your intent in addition to the action (assuming you use BuildConfig and are in your app module, otherwise you can also use context.packageName)
3. I'm afraid this screen will always be shown using the system language because the user is actually leaving your app to be redirected to a system settings screen.

**Comment by johnjohndoe** [comment]
2. Not sure what goes wrong here. I am using the following intent:

    ``` kotlin
    val intent = Intent(ACTION_REQUEST_SCHEDULE_EXACT_ALARM)
        .setData("package:${BuildConfig.APPLICATION_ID}".toUri())
    scheduleExactAlarmsPermissionRequestLauncher.launch(intent)
    ```

**Comment by cbeyls** [comment]
Maybe your issue is hardware-related? I tested my implementation on the emulator and on a Pixel 4a.
You can always test `AlarmManager.canScheduleExactAlarms()` instead when the activity result arrives.

**Comment by johnjohndoe** [comment]
I tested it on various devices and emulators - see: https://github.com/EventFahrplan/EventFahrplan/pull/614

Yes, I also check with `canScheduleExactAlarms()`, see: https://github.com/EventFahrplan/EventFahrplan/blob/0d72920100783928d4befb3052ba26f2bb638a0c/app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/SessionDetailsFragment.kt#L148-L164
