### ISSUE TITLE
Adjust App year to 2024

### ISSUE THREAD

**Issue by sphenotux** [EventFahrplan/EventFahrplan#626]
# Environment
- App version: 1.58.0-CLT-Edition
- Android version: 12
- Branch: N.A.
- Device:  Huawei P40 lite

# How to reproduce
1. Search "CLT" in F-Droid store
2. Find "Fahrplan 2023" (Bad) 
3. Download, install
4. Open Fahrplan shows topics of 2024. Good. 
5. Select menu on the upper right, three dots: Info
6. Year 2024 is shown, but wrong date in March 2023 (bad, see screenshot) 

# Observed behavior
- see above

# Expected behavior
- Show correct and current dates for 2024

# Related
- N. A. 
![Screenshot_20240216_222034_info metadude android clt schedule](https://github.com/EventFahrplan/EventFahrplan/assets/55288702/9d65b405-d91b-4f29-866a-72a2c263715d)

**Comment by johnjohndoe** [comment]
I already asked the team of [Chemnitzer Linux-Tage](https://chemnitzer.linux-tage.de). Please reach out to them to request an update. Thank you.
