### ISSUE TITLE
Order of speakers changes randomly, causing excessive changelog entries

### ISSUE THREAD

**Issue by girst** [EventFahrplan/EventFahrplan#697]
# Environment
- App version: 1.68.0
- Android version: 14
- Branch: - (via f-droid)
- Device: pixel6

# How to reproduce
1. Refresh the Fahrplan
2. Check the Changelog

# Observed behavior
- Most items in the changelog only had the order of speakers changed (e.g. from 'Sec, Ray' to 'Ray, Sec')
- my guess is that either the API does not return the speakers in the same order every time, or that the app stores the list of speakers in a unordered set.

# Expected behavior
- changed order of speakers should not generate a changelog entry

# Related
- n/a

**Comment by johnjohndoe** [comment]
Correct. See: https://git.cccv.de/hub/hub/-/issues/565

**Comment by johnjohndoe** [comment]
This issue has been resolved by the backend team.
