### ISSUE TITLE
Show scrollbars

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#7]
The different views (details, favorites, changes*) are scrollable but do **not** show scrollbars when users scroll. The alarms screen shows scrollbars.

_*not verified yet._

**Comment by isiko** [comment]
I would like to try and fix this

**Comment by johnjohndoe** [comment]
Great. Please re-evaluate which screens are affected since this issue is rather old. Please reach out if you like to discuss your approach.

**Comment by isiko** [comment]
I already fixed the Favorites page by removing some margins and paddings that had pushed the ScrollBar off the screen (I couldn't see any difference in the layout after removing them, so I figured they wouldn't do anything important)

I'm working on the details layout now, I'm just getting into the structure.

**Comment by isiko** [comment]
Update:
The Details Screen already shows a Scrollbar.
Also, the change list looks like it has the same problem as the favorites page (the layout extends beyond the edge of the screen on both pages), but unfortunately since there are no changes I can't verify that
