### ISSUE TITLE
Date and time system settings

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#70]
Date and time are shown in different parts of the app such as:

- Time column on the side of the tabular view
- Event details
- Share message
- Calendar export

Date and time formatting in these places is hardcoded in the app.
The app should respect formatting preferences of the device resp. user such as:

- Use 24-hour format

---

:point_up: Side note for the implementation: the long term goal is to replace all app date handling with [ThreeTen-Backport libraries](https://www.threeten.org/threetenbp/). It might be possible to do the migraton as part of this issue. Let's discuss.

**Comment by ari-s** [comment]
This is still the case right? Just stumbled upon "2:00 nachm" in the favourites and now I don't know at what time the event is happening :( (german is correct, it's the 12h format that's bothering me)

would be great if times would be displayed in a reasonable format!

**Comment by johnjohndoe** [comment]
> "2:00 nachm" in the favourites and now I don't know at what time the event is happening :( (german is correct, it's the 12h format that's bothering me)

I do not understand. If you are running your device on German and reading "2:00 nachm" why is it unclear when the event takes place? Where is the 12h in this case?

I checked the favorites when I set my device to English. If I use 24h setting or 12h setting it looks reasonable. Can you please explain the exact case?

**Comment by ari-s** [comment]
my phone is set to 24h format and as far as I've noticed uses this everywhere. In the favourites however,  12 hour format is displayed.

sorry for being unclear here. Of course, technically 2:00 is in the afternoon, although 2:00 (24hour-format) feels much more like afternoon then 14:00

**Comment by ideadapt** [comment]
I am on this.
