### ISSUE TITLE
favorites using id and not guid

### ISSUE THREAD

**Issue by exmatrikulator** [EventFahrplan/EventFahrplan#96]
at the schedule file (https://raw.githubusercontent.com/voc/35C3_schedule/master/everything.schedule.xml)
share some events the same id.

if you mark one event in the app as favorite, you have multiple events marked.

**Comment by johnjohndoe** [comment]
@exmatrikulator Can you please provide an example? Feel free to link to the lines in the file.

**Comment by exmatrikulator** [comment]
like on of
- HackspaceDesignPatterns
- Die eigene Stimme hacken
- Freifunk IoT
- Die Wochendämmerung

and you have liked all of them

**Comment by johnjohndoe** [comment]
@saerdnaer Does the backend check for the uniqueness of ids?

**Comment by saerdnaer** [comment]
„Backend“... No only for guid not for the local id. Wiki IDs Start from  1000 - I can add an static offset  of 200 for the pretalx sources, but then would exist favorites break... Also I have to analyse which source uses which I’d range. Another solution are string prefixes, Or does EventFahrplan require the Id to be an integer?

The long term solution for EventFahrplan is to switch to uuid.

**Comment by saerdnaer** [comment]
As a quick fix, I addded id offsets with https://github.com/voc/schedule/commit/932d9049a8f2e79ea5e120c89ff4fc3b3eda6bc2

**Comment by johnjohndoe** [comment]
@saerdnaer Thank you for fast patch!
@exmatrikulator Can you please verify and let us know if this solves the problem on your side? I believe you need to fetch the recent schedule data at least once.

**Comment by exmatrikulator** [comment]
looks better, thanks!
